### ISSUE TITLE
IntelliJ IDEA 2022.3.2 (Community Edition)

### ISSUE THREAD

**Issue by xuZhu-lab** [ignatov/intellij-erlang#1004]
erlang 25.3
the newest plugin(0.11.1162) does not support the keywords (maybe...else...end) and symbols (?=) 
![image](https://user-images.githubusercontent.com/3363842/224273441-c060e898-3bc9-4444-a534-366077ddba5e.png)

**Comment by zyuyou** [comment]
[intellij-erlang-0.11.1163.zip](https://github.com/ignatov/intellij-erlang/files/11109614/intellij-erlang-0.11.1163.zip)

`0.11.1162` is not support yet, IDEA-2022 can use `0.11.1163` above, Or IDEA-2023 can use the latest one.
