### ISSUE TITLE
Maybe expression (feature `maybe_expr`) not supported.

### ISSUE THREAD

**Issue by ShawnMcCool** [ignatov/intellij-erlang#1007]
![image](https://user-images.githubusercontent.com/560749/230880709-098e40fb-eee4-407d-837f-29f53ed62335.png)

The `maybe_expr` feature appears to not be supported. Perhaps this PR could resolve it?

https://github.com/ignatov/intellij-erlang/pull/1005

**Comment by kvakvs** [comment]
I believe I merged the contribution by @zyuyou some weeks ago, but was it released since then? I do not control that.

**Comment by ignatov** [comment]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/426890/235943923-7dbdd1f4-e833-43b0-92ba-0dbde13d46a6.png">
updated in 0.11.1197, https://plugins.jetbrains.com/plugin/7083-erlang/versions/stable/327858
