### ISSUE TITLE
"erl: not found" while trying to setup rebar3 path

### ISSUE THREAD

**Issue by meppu** [ignatov/intellij-erlang#1008]
I use erlang with asdf-vm. And i installed rebar3 with `./rebar3 local install`. While trying to setup rebar3 it gives me following error:

![image](https://github.com/ignatov/intellij-erlang/assets/112294217/7605fb96-4ba9-4699-9433-6fdb7a4b7acb)

But i have `erl`:

![image](https://github.com/ignatov/intellij-erlang/assets/112294217/f2db5bc7-cbdd-4640-aa39-fe3aa6ea965f)
![image](https://github.com/ignatov/intellij-erlang/assets/112294217/e70230e1-dd5d-43ea-8229-3efd7733ee34)

**Comment by kvakvs** [comment]
See that Erlang is visible for your user, not just shell. That's in .profile and you need to log out.

**Comment by meppu** [comment]
Looks like it is fixed when i add these to the `.profile`:
```bash
. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/completions/asdf.bash"
```

I don't know if this is the Right Way™ but it works. Thanks for the info!
