### ISSUE TITLE
Syntax error on `maybe' function in editor

### ISSUE THREAD

**Issue by kpy3** [ignatov/intellij-erlang#1009]
With adding support of new `maybe` syntax editor start threat functions named `maybe` as error:

<img width="266" alt="image" src="https://github.com/ignatov/intellij-erlang/assets/17118/95016cc1-48ae-4cb6-b694-192e2a3dfaa7">

**Comment by kvakvs** [comment]
Ideas to fix this 

- parse `maybe` as atom before Erlang 25
- Or to parse it as keyword but allow it in function head where the name goes
- And also must not parse `maybe` in function body as maybe-expression if before Erlang 25

Some things i do not have experience of doing in IntelliJ/GrammarKit
