### ISSUE TITLE
get in trouble: Failed to setup debugger environment

### ISSUE THREAD

**Issue by swingczy** [ignatov/intellij-erlang#1018]
Hello, please help me ! I don't know how to fix it.
    I created a hello_world erlang project without rebar3, and a `main.erl`,
    and a function `start() -> io:format("hello erlang~n").`, it can be runned but cannot be debugged, and the following error message occured in debug window:

Failed to setup debugger environment

Thanks a lot!

**Comment by swingczy** [comment]
Must I use rebar3?

**Comment by obi458** [comment]
How do you solve tihis issue?

**Comment by swingczy** [comment]
@obi458 I didn't, I gave up😅
