### ISSUE TITLE
with otp 27.0 plugin won't see many exports from the 'erlang' module

### ISSUE THREAD

**Issue by brigadier** [ignatov/intellij-erlang#1043]
<img width="410" alt="Screenshot_20240909_205640" src="https://github.com/user-attachments/assets/18398c13-e919-4073-9b99-ede8003424e0">

see screenshot. 
No such problem with OTP 26 and the same code.

It's because it cannot parse erlang.erl anymore after introduction of triple-quoted strings (?)

**Comment by brigadier** [comment]
Many other modules from stdlib also contain new syntax and are parsed with the current version of the plugin

**Comment by ignatov** [comment]
Ouch! Thanks for reporting, it looks like I have plenty of. work to support Erlang 27 :)

**Comment by ignatov** [comment]
<img width="614" alt="image" src="https://github.com/user-attachments/assets/f354a8e9-19b3-4e26-934e-1bfbffabacb3">
on the way
