### ISSUE TITLE
env: escript: No such file or directory

### ISSUE THREAD

**Issue by bryanhughes** [ignatov/intellij-erlang#189]
Howdy, first of all, thank you for your hard work. 

I have a valid and working rebar - I can type 'rebar compile' on the command line and it builds correctly.  I created a Rebar configuration for compile.  When I Run it, I get:

/Users/bryan/projects/wobblesoft/engineering/gomachine-server/rebar compile
env: escript: No such file or directory

escript is present on my system:

$ which escript
/usr/local/bin/escript

Also, I am using IntelliJ 12 with the latest Erlang plugin.

**Comment by bryanhughes** [comment]
Sorry to re-open this, but I am at my wits end. I have a new MacBook Pro and with 10.10.4 and I am not able to get PATH to stick in IntelliJ 14. Here is what I have tried:

sudo launchctl setenv PATH /usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin:/Users/bryan/riak/riak-2.1.1/rel/riak/bin:/Users/bryan/erlang/R16B03-1/bin

When I run rebar I get ```env: escript: No such file or directory```

If I open Terminal in IJ and type env, the PATH is ```PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin```

I even created a launchctl plist in  /Library/LaunchAgent:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>path</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/launchctl</string>
		<string>setenv</string>
		<string>PATH</string>
		<string>/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin:/Users/bryan/riak/riak-2.1.1/rel/riak/bin:/Users/bryan/erlang/R16B03-1/bin</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>```

Nothing works, I can not get IntelliJ and the plugin to pick up my environment. I dont understand why you just dont use the path from the Erlang facade/SDK?

**Comment by deadok22** [comment]
Hi @bryanhughes!

I remember fixing this exact problem: https://github.com/ignatov/intellij-erlang/issues/488. In the fix for https://github.com/ignatov/intellij-erlang/issues/488 I've changed the code so that all child processes inherit IntelliJ's environment.

So it looks, like you don't have your PATH set correctly.

To find out IntelliJ's PATH, you can open ```IDE Scripting Console``` (Tools -> IDE Scripting Console), selecting Groovy as your console language, and running (select the code you want to run and press meta+enter):
```
System.getenv("PATH")
```

**Comment by bryanhughes** [comment]
Unfortunately when I try to run the snippet, I get:

```1:55:48 PM Error running ide-scripting.groovy: Module is not specified``

I have attached a screen shot to show the project structure and there is indeed a Module defined. When I edit the target to run the script, the only selection in the Modules drop down is [none]

![screen shot 2015-08-10 at 1 56 40 pm](https://cloud.githubusercontent.com/assets/21214/9184111/2f0b2c06-3f68-11e5-9827-62f32a8f156c.png)

Also, I went ahead and downloaded and installed the build referenced in #488, but no changes.

**Comment by deadok22** [comment]
You're running it as a groovy run configuration - running it as an IDE console script is a different action (just hit meta+enter)

**Comment by bryanhughes** [comment]
```> System.getenv("PATH")
=> /usr/bin:/bin:/usr/sbin:/sbin```

Here is the output if I open Terminal and type env, which different:

```bash
Yetitronic:gofactory_gomachine bryan$ env
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/gm/v4nyfmpj3091wxdpwwdbgq040000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.eOPWqt6tdL/Render
USER=bryan
RIAK_HOME=/Users/bryan/riak/riak-2.1.1/rel/riak
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.iEW5K8ZH1t/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/bryan/Dropbox/home/projects/gofactory/gofactory_gomachine
ERL_HOME=/Users/bryan/erlang/R16B03-1
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/bryan
LOGNAME=bryan
LC_CTYPE=en_US.UTF-8
_=/usr/bin/env
Yetitronic:gofactory_gomachine bryan$ 
```

I am confused as to why it is not getting the PATH from launchctl. Here is the result:

```
bryan@Yetitronic:~$ launchctl getenv PATH
/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin:/Users/bryan/riak/riak-2.1.1/rel/riak/bin:/Users/bryan/erlang/R16B03-1/bin
```

**Comment by deadok22** [comment]
AFAIK, environment variables on macs are set separately for applications run from terminal and for ones run through dock. I don't have a mac, sorry =)

As to using variables set via launchctl, I've seen people suggesting restarting the dock with ```osascript -e 'tell app "Dock" to quit'```.

**Comment by bryanhughes** [comment]
Your suggestion of:

```
osascript -e 'tell app "Dock" to quit'
```

worked. Thank you!
