### ISSUE TITLE
Cannot Detect SDK Version

### ISSUE THREAD

**Issue by aantono** [ignatov/intellij-erlang#31]
On both Linux CentOS and OSX Mountain Lion, when attempting to add Erlang SDK, get an error saying that "Cannot Detect SDK Version" - "Probably SDK installed in '/opt/local/installs/erlang' is corrupt"

The version is not corrupt, works just fine.

The problem went away, when selected ' /opt/local/installs/erlang/lib/erlang/' instead.  Without explicit documentation of such, it is difficult to know and guess that this is the directory that needs to be provided in order for it to work.

**Comment by myles-mcdonnell** [comment]
Thanks @deadok22 

For reference;  On Yosemite with Erlang installed from Rudix (http://rudix.org/packages/erlang.html) path to SDK is /usr/local/lib/erlang

**Comment by FlowerWrong** [comment]
I have the same issue on ubuntu 14.04 with idea 14.1.4.
When I install erlang with apt-get, it worked.
But after I install erlang with kerl or build from souce code, it does not work.

**Comment by deadok22** [comment]
Hi @FlowerWrong,

Please, share ```tree``` output for your Erlang installation directory.

**Comment by FlowerWrong** [comment]
@deadok22 
```ruby
$ pwd
/home/yy/software/erlang/175
```
```ruby
$ tree -L 2
.
├── activate
├── bin
│   ├── ct_run
│   ├── dialyzer
│   ├── epmd -> ../erts-6.4/bin/epmd
│   ├── erl
│   ├── erlc
│   ├── escript
│   ├── no_dot_erlang.boot
│   ├── run_erl
│   ├── start
│   ├── start.boot
│   ├── start_clean.boot
│   ├── start_erl
│   ├── start_sasl.boot
│   ├── start.script
│   ├── to_erl
│   └── typer
├── erts-6.4
│   ├── bin
│   ├── doc
│   ├── include
│   ├── lib
│   ├── man
│   └── src
├── Install
├── lib
│   ├── asn1-3.0.4
│   ├── common_test-1.10
│   ├── compiler-5.0.4
│   ├── cosEvent-2.1.15
│   ├── cosEventDomain-1.1.14
│   ├── cosFileTransfer-1.1.16
│   ├── cosNotification-1.1.21
│   ├── cosProperty-1.1.17
│   ├── cosTime-1.1.14
│   ├── cosTransactions-1.2.14
│   ├── crypto-3.5
│   ├── debugger-4.0.3
│   ├── dialyzer-2.7.4
│   ├── diameter-1.9
│   ├── edoc-0.7.16
│   ├── eldap-1.1.1
│   ├── erl_docgen-0.3.7
│   ├── erl_interface-3.7.20
│   ├── erts-6.4
│   ├── et-1.5
│   ├── eunit-2.2.9
│   ├── gs-1.5.16
│   ├── hipe-3.11.3
│   ├── ic-4.3.6
│   ├── inets-5.10.6
│   ├── jinterface-1.5.12
│   ├── kernel-3.2
│   ├── megaco-3.17.3
│   ├── mnesia-4.12.5
│   ├── observer-2.0.4
│   ├── odbc-2.10.22
│   ├── orber-3.7.1
│   ├── ose-1.0.2
│   ├── os_mon-2.3.1
│   ├── otp_mibs-1.0.10
│   ├── parsetools-2.0.12
│   ├── percept-0.8.10
│   ├── public_key-0.23
│   ├── reltool-0.6.6
│   ├── runtime_tools-1.8.16
│   ├── sasl-2.4.1
│   ├── snmp-5.1.1
│   ├── ssh-3.2
│   ├── ssl-6.0
│   ├── stdlib-2.4
│   ├── syntax_tools-1.6.18
│   ├── test_server-3.8
│   ├── tools-2.7.2
│   ├── typer-0.9.8
│   ├── webtool-0.8.10
│   ├── wx-1.3.3
│   └── xmerl-1.3.7
├── misc
│   ├── format_man_pages
│   └── makewhatis
├── releases
│   ├── 17
│   ├── RELEASES
│   ├── RELEASES.src
│   └── start_erl.data
└── usr
    ├── include
    └── lib

67 directories, 23 files
```

**Comment by deadok22** [comment]
@FlowerWrong your directory structure looks good - make sure your IDE process has permissions to execute bin/erl and bin/erlc.

I've tried building Erlang 17.5 with kerl, and it works just fine.

How exactly does it fail in your case? It won't allow you to select /home/yy/software/erlang/175 as SDK root?

**Comment by FlowerWrong** [comment]
@deadok22 The error is `Unknown Erlang version at /home/yy/software/erlang/175`.
See:
![2015-08-28 11 54 51](https://cloud.githubusercontent.com/assets/5362640/9538894/4de913aa-4d7c-11e5-9c09-341d94699b22.png)
![2015-08-28 11 55 05](https://cloud.githubusercontent.com/assets/5362640/9538899/5f99db16-4d7c-11e5-80c5-2633905275a8.png)

**Comment by deadok22** [comment]
Ok, what does your log say, @FlowerWrong? (see https://intellij-support.jetbrains.com/hc/en-us/articles/206827517-Locating-IDE-log-files for instructions on locating your log files)

**Comment by FlowerWrong** [comment]
:disappointed: No log at all. I clear the log file before config it, and after the failed config, it still empty.
![2015-08-28 18 08 50](https://cloud.githubusercontent.com/assets/5362640/9544050/22b710a4-4db0-11e5-91ac-1692c8a7bb9b.png)

**Comment by deadok22** [comment]
@FlowerWrong Oh, I forgot logging is not in released version yet - please, try the plugin from https://github.com/ignatov/intellij-erlang/releases - it should log unsuccessful attempts to setup your SDK.

**Comment by FlowerWrong** [comment]
@deadok22 I reinstall the intellig-erlang with pre-release [#778](https://github.com/ignatov/intellij-erlang/releases/tag/%23778). It worked. :+1:

**Comment by deadok22** [comment]
Good. It's https://github.com/ignatov/intellij-erlang/issues/614 you were facing.

**Comment by lionnt** [comment]
Hello, 

On SUSE (SLES11) when trying to add folder which contains erl and erlc as Erlang SDK  the error appears "The selected directory is not a valid home for Erlang SDK"

IntelliJ IDEA version is idea-IC-171.3566.24
Erlang for IntelliJ IDEA version is 0.9.9.35

![screen1](https://cloud.githubusercontent.com/assets/12517687/23414193/568a79de-fddb-11e6-9b13-72e2ca227272.PNG)


Thanks in advance!

**Comment by ignatov** [comment]
Please attach your logs *Help > Show logs in...*.

Sergey Ignatov

**Comment by lionnt** [comment]
Hello Sergey,

I've fixed the problem. The reason of the problem was in the variable OTP_ROOT which was incorrectly set to /opt/otp. In my case OTP is in the /local/scratch/enatlvo/git/sgc/deps/otp/19.1.6-1.3.2/
After pointing to the real otp directory and then opening IntelliJ IDEA I can configure Erlang SDK. No errors.

Sorry for inconvenience and have a nice day!

**Comment by ignatov** [comment]
@lionnt Nice to hear that.
