### ISSUE TITLE
Inject references into spawn call parameters

### ISSUE THREAD

**Issue by calebh** [ignatov/intellij-erlang#398]
When using a macro as either the Module or Function parameter of the spawn function, the plugin says that the function is unused. See the picture for an example.

Edit: issue also occurs when using apply
Edit 2: Warning occurs in Erlang compiler as well. Please close this issue.

![bad_unused_function_notification](https://f.cloud.github.com/assets/542102/1844256/ec81f482-7510-11e3-887f-e912168d3f07.png)

**Comment by deadok22** [comment]
Indeed, the code you shared is invalid as you cannot call spawn or apply on functions which are not exported.
