### ISSUE TITLE
Rebar on Windows

### ISSUE THREAD

**Issue by deadok22** [ignatov/intellij-erlang#432]
There are some special cases to handle when using Rebar on Windows. (rebar.bat, etc)

**Comment by DrWifey** [comment]
I'm trying to add rebar to configuration of my Intellij IDEA 14. I downloaded source of rebar, run bootstrap.bat and added path where rebar (and rebar.cmd) located to PATH variable, Still getiing an error "Rebar executable path is not specified correctly"

**Comment by deadok22** [comment]
The fix is available in the latest build at https://github.com/ignatov/intellij-erlang/releases

**Comment by DrWifey** [comment]
It works! Thank you so much.

**Comment by deadok22** [comment]
You're welcome!

**Comment by cc14514** [comment]
did support rebar3 ?

**Comment by deadok22** [comment]
Please, use search: https://github.com/ignatov/intellij-erlang/issues/704
