### ISSUE TITLE
Rebar executable path is not specified correctly

### ISSUE THREAD

**Issue by golondrino** [ignatov/intellij-erlang#469]
I've compiled Rebar in Windows successfully...and there is a rebar file in the directory where I got "bootstrap.bat"!
How can I set "Rebar" path correctly in Intellij? If I'm specifying it where it's, e.g. in the folder where I launched bootstrap.bat file and then got rebar file... Can you guide me through? 
Thanks before hand.

**Comment by deadok22** [comment]
The fix is available in the latest build at https://github.com/ignatov/intellij-erlang/releases
