### ISSUE TITLE
variable is unbound when the variable is defined in case statement 

### ISSUE THREAD

**Issue by gopig** [ignatov/intellij-erlang#483]
![image](https://cloud.githubusercontent.com/assets/395473/3504365/5e133518-0646-11e4-8b9e-cde7f98249dc.png)

**Comment by gajatko** [comment]
Other case:
```erlang
case true of
        true ->
            X=x;
        _ ->
            X=x;
    end,
case true of
        true ->
            Z=X, % variable unbound
        _ -> ok
    end
```

**Comment by NobbZ** [comment]
X should be unbound there, because the X bound in the if is not in scope
anymore in the case. If you really have the correct value of X in the case
I'd consider this a bug in erlangs scoping of names.

Jacek <notifications@github.com> schrieb am Do., 14. Jan. 2016 15:53:

**Comment by gajatko** [comment]
Nope, in erlang
```erlang
case true of
        true ->
            X=x;
        _ ->
            X=x;
end,
```
is equivalent to
```erlang
X=case true of
        true ->
            x;
        _ ->
            x;
end,
```
It's just another notation.
