### ISSUE TITLE
rebar version not resolving under MacOSX 10.9

### ISSUE THREAD

**Issue by alxrt** [ignatov/intellij-erlang#488]
Maybe it because ExtProcessUtil.restrictedTimeExec(..) in src/org/intellij/erlang/rebar/settings/RebarConfigurationForm.java, function validateRebarPath() returns empty string in some (?) cases.

**Comment by deadok22** [comment]
The fix will be available in the next pre-release build.

**Comment by deadok22** [comment]
Thanks for reporting the issue!

You can grab a fresh build at: https://github.com/ignatov/intellij-erlang/releases
