### ISSUE TITLE
Customize erlc compilation arguments

### ISSUE THREAD

**Issue by saleyn** [ignatov/intellij-erlang#554]
Is there a way to pass custom arguments to the erlc compiler?  I.e. I'd like to have two debug configurations where one would set -DDEBUG, and the other one would not. Is this doable?

**Comment by saleyn** [comment]
Is it possible to force IntelliJ IDEA to run "make" in the project's root as opposed to erlc to build beam files?

**Comment by deadok22** [comment]
Hi, @saleyn,

Currently defining compiler macros is not available, but it's surely coming with preprocessor support we're planning to introduce soon, stay tuned.

**Comment by deadok22** [comment]
Custom compiler arguments can be added in 'Settings' -> 'Build, Execution, Deployment' -> 'Compiler' -> 'Erlang Compiler'. 

The latest plugin build is available [here](https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Erlang&tab=projectOverview)
