### ISSUE TITLE
Erlang syntax parser error

### ISSUE THREAD

**Issue by saleyn** [ignatov/intellij-erlang#558]
The code parser seems to fail to recognize that single quoted atom names are valid function names. E.g. in the example below the function names will be highlighted as syntax errors:
```erlang
'LOGIN_REPLY'(timeout, #state{name=Name} = State) ->
    error_logger:warning_msg("~s: timeout waiting for login reply!\n", [Name]),
    {stop, no_login_reply, State};
'LOGIN_REPLY'(#logon{session_id=SID}, State) ->
    {next_state, 'WAIT_FOR_DATA', State#state{session=SID}, ?TIMEOUT};
```
![image](https://cloud.githubusercontent.com/assets/272543/5809859/925e33c2-a00b-11e4-978a-bf6ef4b20166.png)

**Comment by deadok22** [comment]
Hi @saleyn, 

Thanks for reporting, a fresh build will be published soon.

**Comment by deadok22** [comment]
@saleyn, feel free to grab a fresh build at https://github.com/ignatov/intellij-erlang/releases
