### ISSUE TITLE
Unresolved Erlang functions

### ISSUE THREAD

**Issue by youngkin** [ignatov/intellij-erlang#559]
Hi,

I'm using Intellij 14 Ultimate with the intellij-erlang plugin. I have warnings in the code for unresolved functions with standard Erlang functions (e.g., Unresolved function 'init:stop/0'). I'm also using 3rd party libraries (e.g., amqp_client) that have a similar problem. I'm new to Intellij so I may not have set up the project correctly. Any help would be appreciated.

Thanks,
Rich

**Comment by deadok22** [comment]
Hi @youngkin!

Most probably, you have your project or modules' SDK not set to an Erlang SDK. Check if that is the case. If not, please, share more details on what your setup looks like.

**Comment by youngkin** [comment]
I noticed the SDK setting text was red. Thought that looked odd and sure enough, it wasn't valid. Fixed it and all is good now. One thing that still isn't working. I'm using a 3rd party erlang library (amqp for RabbitMQ). I'm still getting warnings on this. I tried defining the amqp ebin directory location under ProjectStructure/Modules, but that didn't work (didn't think it would since it asks only if the library is Java or from Maven). Help on this is also appreciated. Thanks!

**Comment by deadok22** [comment]
The plugin doesn't support using IntelliJ libraries. So the workaround for now is to create an Erlang module at ProjectStructure/Modules. Be sure to have module's output path set correctly, and source/include directories marked appropriately. Also don't forget to add the created module as a dependency for you project's module(s).

Please share screenshots if you face any further issues, - it's somewhat hard to guess what your setup is =)

**Comment by Deepro** [comment]
I'm facing the same issue. It happens to me for such declarations like

fun erlang:'>'/2

I'm sure the Erlang STD has been specified correctly.

**Comment by aaronlelevier** [comment]
This SO answer works to resolve 3rd party unresolved functions: https://stackoverflow.com/a/53046579
