### ISSUE TITLE
Cannot start local node with long names for debugging a remote node

### ISSUE THREAD

**Issue by ZeWaren** [ignatov/intellij-erlang#561]
Commit 0fb9a7c572493a017bbf825ff6615fb57ab356e1 introduced the ability to debug remote Erlang node using -name or -sname.

Unfortunately, when "Use short name" in the debug configuration form is unticked, connecting to a remote long-named node does not seem to work.

**What should happen**:
The local node starts successfully with `-name debugger_node_1234@something.example.com` and connects to the remote node.

**What happens**:
The debugger is started the following way:

```
"C:\Program Files\erl6.2\bin\erl.exe" -pa C:\Users\MyUser\AppData\Local\Temp\intellij_erlang_debugger_22.tmp -pa X:/testerlangide/out/production/testerlangide -pa X:/testerlangide -run debugnode main 20237 -name debugger_node_1422952492733 -noshell
```

Which is invalid, since `debugger_node_1422952492733` looks like a short name and not a long name.

Erl complains:
```
{error_logger,{{2015,2,3},{9,34,52}},"Can't set long node name!\nPlease check your configuration\n",[]}
```

**Why it happens**:
The node name is generated in `src/org/intellij/erlang/debugger/remote/ErlangRemoteDebugRunningState.java`:
```java
protected List<String> getErlFlags() {
     String nodeNameFlag = myConfiguration.isUseShortNames() ? "-sname" : "-name";
     String nodeName = "debugger_node_" + System.currentTimeMillis();
     return ContainerUtil.list(nodeNameFlag, nodeName);
}
```

**What might be done**:
Adding a configuration value to specify the host name in the configuration form could do the trick. This value could default to the system hostname.

**Comment by deadok22** [comment]
Hi, @ZeWaren!

You're right, it should use something like "debugger_node_xxx.$(hostname)".

The hostname can be obtained via ```java.net.InetAddress.html#getCanonicalHostName```. Why won't you provide a pull request? You do already have an environment to test the patch anyway =)

**Comment by ZeWaren** [comment]
Hey @deadok22 
I'll create a pull request in the next couple days if everything goes well.

**Comment by deadok22** [comment]
Good! Happy hacking there!

**Comment by ZeWaren** [comment]
Pull request created. Man, remote debugging is so pleasant.
