### ISSUE TITLE
Mac: Cannot import rebar project

### ISSUE THREAD

**Issue by nilskassube** [ignatov/intellij-erlang#563]
Environment: Mac OS X Yosemite 10.10.2, IntelliJ CE 14.0.3

I created a dummy project on the shell with rebar create-app appid=Foo which worked fine.

Added the Erlang SDK to IntelliJ, entered the path to my rebar executable (in ~/bin and also tried a symlink to /usr/local/bin) in the settings. I tried using launchctl to add the path to IntelliJ, also tried to add LSEnvironment to the Info.plist, however the rebar version string is never shown in the settings but also no error message. 

If I try to import the rebar project I also don't see the rebar version string in the dialog and "Next" has no function. No error message. 

I assume the rebar executable is not found, however I have tried all of the ways described in https://superuser.com/questions/476752/setting-environment-variables-in-os-x-for-gui-applications -- it simply does not work.

**Comment by nilskassube** [comment]
I added an External Tool and there it works when launched from IntelliJ. 

/usr/local/bin/rebar version
rebar 2.5.1 17 20141113_100502 git 2.5.1-39-g6e6b0fd

Process finished with exit code 0

**Comment by deadok22** [comment]
Hi, @nilskassube!

I've addressed the issue in one of the latest commits. Please try the latest pre-release build from https://github.com/ignatov/intellij-erlang/releases

Cheers!

**Comment by deadok22** [comment]
Duplicates https://github.com/ignatov/intellij-erlang/issues/488
