### ISSUE TITLE
Version 0.5.10 - Project SDK is not defined Setup SDK does nothing

### ISSUE THREAD

**Issue by riceboyler** [ignatov/intellij-erlang#569]
Using WebStorm 9.0.3, just installed version 0.5.10 of the Erlang plugin - Now all of my Erlang documents have a yellow bar with ```Project SDK is not defined``` and ```Setup SDK``` link to the right. I tried clicking on Setup SDK to no avail. I've made sure that my Erlang SDK path is set correctly in Erlang External Tools.

Is there anything I can do to get rid of this yellow bar?

**Comment by deadok22** [comment]
Thank you for reporting, @riceboyler, it will be fixed soon

**Comment by riceboyler** [comment]
@deadok22 Just for my knowledge, is it due to WebStorm not having support for the Project Structure stuff?

**Comment by deadok22** [comment]
@riceboyler Nope, it's just a silly bug I introduced some time ago

**Comment by deadok22** [comment]
@riceboyler until we fix it, you may use an older build from https://github.com/ignatov/intellij-erlang/releases

**Comment by riceboyler** [comment]
@deadok22 OK, thanks for the info. If it bugs me too much, I'll revert.

**Comment by JeremyOuyang** [comment]
why can't i select my erlang path when i select  home directory for erlang SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64

**Comment by JeremyOuyang** [comment]
why can't i select my erlang path when i select  home directory for erlang SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64

**Comment by JeremyOuyang** [comment]
why can't i select my erlang path when i select  home directory for erlang SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64

**Comment by JeremyOuyang** [comment]
why can't i select my erlang path when i select  home directory for erlang SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64

**Comment by JeremyOuyang** [comment]
why can't i select my erlang path when i select  home directory for erlang SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64

**Comment by JeremyOuyang** [comment]
why can't i select my erlang path when i select  home directory for erlang SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64

**Comment by JeremyOuyang** [comment]
why can't i select my Erlang path when i select  home directory for Erlang_SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64

**Comment by JeremyOuyang** [comment]
why can't i select my Erlang path when i select  home directory for Erlang_SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64.

**Comment by JeremyOuyang** [comment]
why can't i select my Erlang path when i select  home directory for Erlang_SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64.

**Comment by JeremyOuyang** [comment]
why can't i select my Erlang path when i select  home directory for Erlang_SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64.

**Comment by JeremyOuyang** [comment]
why can't i select my Erlang path when i select  home directory for Erlang_SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64.

**Comment by JeremyOuyang** [comment]
why can't i select my Erlang path when i select  home directory for Erlang_SDK, i'm sure my path is correct. i press the ''ok'' button , it's has not any response. my os is win 7 X 64.

**Comment by JeremyOuyang** [comment]
Why can't i select my Erlang path when i select home directory for Erlang_SDK? I'm sure my path is correct. When i press the ''ok'' button , it has not any response. My os is win 7 X 64.
