### ISSUE TITLE
0.5.11 plugin not supported with IntelliJ 14.1

### ISSUE THREAD

**Issue by byyo** [ignatov/intellij-erlang#571]
Updated to the latest IntelliJ version today and was sad to see that the Erlang plugin is not supported in the latest version :(

**Comment by byyo** [comment]
My mistake, I had 0.5.11.139 plugin installed and it didn't auto-update.

**Comment by deadok22** [comment]
Hi @byyo!

You were a bit faster than me on this =) I'm glad it's all well now.
