### ISSUE TITLE
Code Completion Autopopup Error

### ISSUE THREAD

**Issue by maxifly** [ignatov/intellij-erlang#574]
I type:

  "case Var of"

 At that moment, when I type "of" pop-up list appear, and it is worth first item "orber_ifr_fixeddef"
 Then I see how "OF" appears in top of pop-up list, but the focus is on the line does not pass.

Sorry for my English.

**Comment by deadok22** [comment]
Thank you, @maxifly!

I've fixed the issue and spotted some other similar inconveniences - I reported them in https://github.com/ignatov/intellij-erlang/issues/575
