### ISSUE TITLE
Right click on a big project in Project window doesn't work

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#576]
I have a big Erlang project opened in IDEA 14.1.1 (~1000 erl modules, 500k lines of code), Erlang 0.5.11. Every time I try to right click on it in Project window the IDE hangs and my laptop's cooler starts to spin like crazy. After a minute or so the right click menu appears for a fraction of a second and closes immediately after that.

**Comment by deadok22** [comment]
Hi @istocniks!

Please, share a CPU profiling snapshot. Steps to capture it can be found here: https://intellij-support.jetbrains.com/entries/29983118-Reporting-performance-problems

**Comment by istocniks** [comment]
Here they are:
http://cl.ly/1M3H26180v41
http://cl.ly/2s0g0E3T1T3j

**Comment by istocniks** [comment]
It works now, thanks!
