### ISSUE TITLE
Incorrect caret placement in case statement

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#579]
IDEA 14.1.1, Erlang 0.5.11

Here's my Erlang formatting settings:
![screen shot 2015-04-07 at 5 24 07 pm](https://cloud.githubusercontent.com/assets/1018740/7036625/1105bde4-dd4c-11e4-9c69-a24f1930246d.png)

IDE automatically indents the caret too far away when I try to assign case statement result of a variable, indentation goes back to 4 spaces when I do Reformat Code.

Automatic caret placement:
![screen shot 2015-04-07 at 5 30 51 pm](https://cloud.githubusercontent.com/assets/1018740/7036723/9c30e326-dd4c-11e4-8d1c-b009f69ec11c.png)
![screen shot 2015-04-07 at 5 32 02 pm](https://cloud.githubusercontent.com/assets/1018740/7036735/b69e0e5a-dd4c-11e4-94b2-f2d50b14f0a8.png)

After Reformat Code:
![screen shot 2015-04-07 at 5 32 10 pm](https://cloud.githubusercontent.com/assets/1018740/7036738/bb49f360-dd4c-11e4-8cc5-c40e14c53848.png)

**Comment by deadok22** [comment]
Grab a fresh build from: https://github.com/ignatov/intellij-erlang/releases

Auto-indentation should now work better with your settings ('Honor relative' off)
