### ISSUE TITLE
Problems with record autoformatting

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#582]
IDEA 14.1.1, Erlang 0.5.11

Let's assume I have an empty record and my cared is placed inside it's braces:
![screen shot 2015-04-08 at 2 32 05 pm](https://cloud.githubusercontent.com/assets/1018740/7055899/2f535cec-ddfc-11e4-8514-f98680d6fb6b.png)
That's what happen if I hit enter, an extra closing brace is created:
![screen shot 2015-04-08 at 2 32 22 pm](https://cloud.githubusercontent.com/assets/1018740/7055898/2f4f12c2-ddfc-11e4-8170-bd35e3926961.png)

Similar thing happens if the record is not empty:
![screen shot 2015-04-08 at 2 37 21 pm](https://cloud.githubusercontent.com/assets/1018740/7055973/eda90aac-ddfc-11e4-98c0-fa8a2afa0f60.png)
![screen shot 2015-04-08 at 2 37 30 pm](https://cloud.githubusercontent.com/assets/1018740/7055993/014ce7f4-ddfd-11e4-991d-47f38353da59.png)

My code style config:
![screen shot 2015-04-08 at 2 40 45 pm](https://cloud.githubusercontent.com/assets/1018740/7056023/37ea3c6c-ddfd-11e4-8789-3c6ab1eec255.png)

**Comment by deadok22** [comment]
Just so as you know - the buggy behavior was caused by an unmatched left curly brace in code above.

**Comment by deadok22** [comment]
Check out the latest build: https://github.com/ignatov/intellij-erlang/releases/

**Comment by istocniks** [comment]
Not really sure which unmatched left curly brace you are referring to... 
I checked the latest build, an extra brace does not get created any more, but caret still doesn't get indented automatically :(

**Comment by deadok22** [comment]
Please, share an example of incorrect caret indentation - I may have missed some cases.

**Comment by istocniks** [comment]
Thanks for the fast response!
![screen shot 2015-04-13 at 11 04 56 am](https://cloud.githubusercontent.com/assets/1018740/7121970/ff271336-e1cc-11e4-8a4f-e4df3ce0c40f.png)
![screen shot 2015-04-13 at 11 05 03 am](https://cloud.githubusercontent.com/assets/1018740/7121971/ff3c7bae-e1cc-11e4-9bf2-a1fe5ac5c8cc.png)
Here it is, the caret should be automatically indented here, but it's not.

**Comment by deadok22** [comment]
Where does it go instead? What's your tab/indent/continuation indent size?

**Comment by deadok22** [comment]
And also, why would you want it to go there? The formatter will add indentation for each record field assignment anyway.

**Comment by istocniks** [comment]
Take a look at the screenshots, it goes to the same level as the record definition itself.
Here are my settings:
![screen shot 2015-04-13 at 11 15 48 am](https://cloud.githubusercontent.com/assets/1018740/7122194/91efcd38-e1ce-11e4-95e2-a5f0eb3a82f9.png)

**Comment by deadok22** [comment]
Oh, I misread the "caret should be automatically indented here" as if the screenshot would show the correct indentation =)

Thanks!

**Comment by istocniks** [comment]
Thanks again for addressing this, unfortunately I found new bugs after the latest changes :(

* Closing curly brace doesn't appear/disappear automatically when I add/remove opening curly brace if a record is in function body, but it works if a record is part of function argument list.

![screen shot 2015-04-16 at 1 19 55 pm](https://cloud.githubusercontent.com/assets/1018740/7190463/64041f90-e43b-11e4-9f0b-7874e7b9bb9c.png)
![screen shot 2015-04-16 at 1 20 02 pm](https://cloud.githubusercontent.com/assets/1018740/7190464/64063e4c-e43b-11e4-9cb4-f631dd5a4d56.png)
![screen shot 2015-04-16 at 1 20 19 pm](https://cloud.githubusercontent.com/assets/1018740/7190465/6407578c-e43b-11e4-8792-9ae6e94c1e63.png)
![screen shot 2015-04-16 at 1 20 25 pm](https://cloud.githubusercontent.com/assets/1018740/7190466/6409d05c-e43b-11e4-9645-e641c9894dcb.png)

* Continuation indent doesn't work and it's config value has no effect:

![screen shot 2015-04-16 at 1 17 02 pm](https://cloud.githubusercontent.com/assets/1018740/7190403/ec804534-e43a-11e4-8ff3-bb896ed90844.png)
![screen shot 2015-04-16 at 1 17 10 pm](https://cloud.githubusercontent.com/assets/1018740/7190404/ec815780-e43a-11e4-84eb-026905a87bee.png)

**Comment by deadok22** [comment]
Could you create separate issues for these, please?

Once again, thank you very much for reporting issues. It's really unfortunate to have new bugs appearing after fixing the old ones, but we're increasing test coverage, so it'll eventually get better =)

**Comment by istocniks** [comment]
It's a pity that I have no time / enough knowledge to fix these my myself :) Created #594
