### ISSUE TITLE
Incopatible with new version

### ISSUE THREAD

**Issue by maxifly** [ignatov/intellij-erlang#583]
IDEA Uptate info reports that Erlang plugin incompatible with version 14.1.1 (build 141.178)

**Comment by deadok22** [comment]
Hi @maxifly, 

Please, install the plugin again and it will work.

**Comment by maxifly** [comment]
I can not see erlang in IDEA repository

**Comment by deadok22** [comment]
Try uninstalling it first.

**Comment by maxifly** [comment]
I uninstall plugin
And install it again.
Choose Help/Check for Update

I see modal window:
![idea](https://cloud.githubusercontent.com/assets/2596114/7065817/7845bcce-dec4-11e4-8b1a-809a955e212a.jpg)

**Comment by deadok22** [comment]
Oh, I get it now. Ignore the error message, install the new IntelliJ IDEA build, and then install the plugin.
It's a known issue - we've published the plugin v0.5.11 for both IntelliJ IDEA 14.0.* and 14.1.*. Apparently this lead to conflicts in plugin version checking system.

**Comment by maxifly** [comment]
OK. Its work
