### ISSUE TITLE
One more indentation bug

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#587]
IDEA 14.1.1, Erlang master 2c7e79608b733158bba15ace902045272f964143, "Honor Relative" turned of.

Let's assume I have such statement:
![screen shot 2015-04-09 at 3 44 56 pm](https://cloud.githubusercontent.com/assets/1018740/7078619/9e1817d4-decf-11e4-8580-2b498c9ce664.png)
That's what happens if I hit enter, the caret is underindented. 
![screen shot 2015-04-09 at 3 45 07 pm](https://cloud.githubusercontent.com/assets/1018740/7078621/a1dbfce6-decf-11e4-91a3-f056a682b98c.png)
I don't recall having this problem before the latest changes.

**Comment by deadok22** [comment]
Check out the latest build: https://github.com/ignatov/intellij-erlang/releases/

**Comment by istocniks** [comment]
Looks like it works now, thanks a lot! But unfortunately I found another but that I didn't see before the latest changes:
![screen shot 2015-04-13 at 11 10 44 am](https://cloud.githubusercontent.com/assets/1018740/7122096/ca07e490-e1cd-11e4-9791-769ddc142ab5.png)
![screen shot 2015-04-13 at 11 10 52 am](https://cloud.githubusercontent.com/assets/1018740/7122097/ca088de6-e1cd-11e4-8ea4-ba37c4af6569.png)
The caret does not get indented inside function argument brackets any more :(

**Comment by istocniks** [comment]
Should I create a new task for the issue mentioned above?

**Comment by deadok22** [comment]
I've started working on https://github.com/ignatov/intellij-erlang/issues/582 and I've decided to try to unify formatting and indentation where possible, so I'll have this case covered as well. 

There is no need to create a new issue for this as https://github.com/ignatov/intellij-erlang/issues/582 is mentioned here - I'll fix it.

Thank you once again for your bug reports.

**Comment by istocniks** [comment]
Great! Thank you for responding so fast :)
