### ISSUE TITLE
Doesn't support maps on the Erlang Term Files

### ISSUE THREAD

**Issue by loguntsov** [ignatov/intellij-erlang#588]
For example:
#{ a => b }.

writes that:
 # unexpected
and 
'(',',' or <q atom> expected, got '=>'

version of plugin: 0.5.11

**Comment by deadok22** [comment]
Check out the latest build: https://github.com/ignatov/intellij-erlang/releases/

**Comment by loguntsov** [comment]
It works. Thanks.
