### ISSUE TITLE
Debugging with nested source subdirectories

### ISSUE THREAD

**Issue by Vorticity-Flux** [ignatov/intellij-erlang#590]
Debugging of the projects with subfolders in the source folder seem to have some problems.

I have a rebar project with the following structure:
```
/
├ src/
│    └ subdir/
│            └ file1.erl
└ rebar.config 
```
Everything works fine apart from the debugging support.
Folders src and src/subdir are marked as Source folders in the Project structure (I have also tried marking only src folder as source to no avail).

When I run debug I get the following in the console:
```
** Invalid beam file or no abstract code: file1
```
If I move file1.erl from src/subdir to src everything works as expected.
Either I am missing some basic set up (which is a real possibility :) or sources from src subfolders are not being supplied to the debugger.

**Comment by deadok22** [comment]
Could you please share structure of your project output directory?

And, I guess, you're right - the most probable reason is source files not being available at run time.

**Comment by Vorticity-Flux** [comment]
I am using default rebar configuration.
.app and .beam files are put into the flat ebin folder. I.e.
```
/
├ ebin/
│     ├ theapp.app
│     └ file1.beam
├ src/
│    └ subdir/
│            └ file1.erl
└ rebar.config 
```

Sample project
http://www.filedropper.com/test_50

**Comment by deadok22** [comment]
Thank you, @Vorticity-Flux.

**Comment by deadok22** [comment]
The issue was fixed along with https://github.com/ignatov/intellij-erlang/issues/608.
