### ISSUE TITLE
Variable name autocompletion

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#593]
IDEA 14.1.1, Erlang 815618228d0072798c285cf424db25a18ad7c0ed

Pretty ofter when I type a variable name and hit enter it gets changed to something autocompleted, this happens even if I type fast.

![screen shot 2015-04-16 at 1 37 26 pm](https://cloud.githubusercontent.com/assets/1018740/7190842/d0bd4b96-e43d-11e4-9a48-c8f69bde8e07.png)
![screen shot 2015-04-16 at 1 37 40 pm](https://cloud.githubusercontent.com/assets/1018740/7190843/d0becc5a-e43d-11e4-96eb-1527235a65be.png)

I assume it's part of my local configuration or something but I don't recall having such issues with Java.

**Comment by brigadier** [comment]
Similar thing happens with 'case ... of' autocompletion. When I type 'of' very fast, the first thing in the autocompletion combobox is 'orber_ifr_fixeddef'. After a moment 'of' appears right above 'orber_ifr_fixeddef', but the cursor is already positioned on 'orber_ifr_fixeddef', so when I press enter it inserts 'orber_ifr_fixeddef'.
 It is very annoying.

![screen](http://i.imgur.com/DPUPmD8.png?1)

**Comment by deadok22** [comment]
A build with this issue fixed is available here: https://github.com/ignatov/intellij-erlang/releases
