### ISSUE TITLE
How to debugger or eunit a OTP project?

### ISSUE THREAD

**Issue by allran** [ignatov/intellij-erlang#598]
I have read this page:https://www.jetbrains.com/idea/help/getting-started-with-erlang.html#d187806e35

And I am still very confused that how to debugger or eunit a OTP project, is there a video about that? 
I want find something in the youtube, but it is not what I want。

**Comment by deadok22** [comment]
Hi @allran, 

you've described your problem too vaguely. Please, share more details on your project, your setup, etc.

**Comment by allran** [comment]
For example, 

%%%-------------------------------------------------------------------
-module(name_server).
-author("allran").
-import(server,[rpc/2]).

%% API
-export([init/0, add/2, whereis/1, handle/2]).


add(Name, Place) ->
  rpc(name_server, {add, Name, Place}).
whereis(Name) ->
  rpc(name_server, {whereis, Name}).


init() ->
  dict:new().


handle({add, Name, Place}, Dict) ->
  {ok, dict:store(Name, Place, Dict)};
handle({whereis, Name}, Dict) ->
  {dict:find(Name, Dict), Dict}.








%%%-------------------------------------------------------------------
-module(server).
-author("allran").

%% API
-export([start1/0, start/2, rpc/2]).

start1()->
  start(name_server, name_server).

start(Name, Mod) ->
  io_lib:print("server start"),
  register(Name, spawn(fun()->loop(Name, Mod, Mod:init()) end)).

rpc(Name, Request) ->
  Name ! {self(), Request},
  receive
    {Name, Response} -> Response
  end.

loop(Name, Mod, State) ->
  receive
    {From, Request} ->
      {Response, State1} = Mod:handle(Request, State),
      From ! {Name, Response},
      loop(Name, Mod, State1)
  end.







For test, 

1> server:start(name_server_pid, name_server).
true
2> name_server:add(allran, "abcdefg").
ok
3> name_server:whereis(allran).
{ok, "abcdefg"}






About erlang debugger:start(), i know how to use it.
But when i use Interllij , i have no idea to use it.In short, i want to step by step debugging with interllij。

**Comment by deadok22** [comment]
Until we have https://github.com/ignatov/intellij-erlang/issues/340 or https://github.com/ignatov/intellij-erlang/issues/556 resolved, the only way to debug your OTP application/gen-server is to create a run configuration for a function, which would run your application.

In your case you can something like this and then debug it:

```erlang
debug_server() ->
  true = server:start(name_server_pid, name_server),
  ok = name_server:add(allran, "abcdefg"),
  {ok, "abcdefg"} = name_server:whereis(allran).
```
