### ISSUE TITLE
init terminating in do_boot()

### ISSUE THREAD

**Issue by kanga-roo** [ignatov/intellij-erlang#600]
![fac1 ja](https://cloud.githubusercontent.com/assets/12368392/7549079/efa621f6-f66a-11e4-92ff-16c3d68ac562.png)

**Comment by deadok22** [comment]
The error message says all you need to know here. As you can see, your entry point is ```fac:main(fac(N))``` where ```N``` is, of course, unbound. Check your function arguments in run configuration settings.

**Comment by kanga-roo** [comment]
Thank you, Sergey.

**Comment by kanga-roo** [comment]
Dear Sergey, Please excuse my lack of understanding. This is my first attempt with IJ.I have tried entering all the different function arguments I can think of in run configurations with the same error. Would you mind giving me a more explicit clue? Many thanks.

**Comment by deadok22** [comment]
It's not the place to ask for such help as it has nothing to do with IntelliJ.

Anyway, your program seems weird, a correct argument would be ```['3']```

**Comment by kanga-roo** [comment]
It is from page 165 of Joe's book. I am using it to learn Erlang and IJ. I appreciate your understanding, guidance and assistance. Thank you for the great work you do. Best wishes to you and your colleagues from Australia.

**Comment by deadok22** [comment]
I've never read it. I suppose, the point behind it is to get you familiarized with erlang's type system. Hence, the weird conversions =)

You're welcome. Good luck there!

**Comment by kanga-roo** [comment]
I enjoyed your joint presentation of 'Erlang IDE done right' in 2014. I will keep trying different arguments. Enjoy spring time!
