### ISSUE TITLE
{undef,[{fact,fac,[1],[]}

### ISSUE THREAD

**Issue by kanga-roo** [ignatov/intellij-erlang#601]
dear sergey, I have been googling as hard as I can and I cannot find a clue as to what I am doing wrong.
would you mind giving me another clue where I should be looking. many thanks.
![fact](https://cloud.githubusercontent.com/assets/12368392/7696938/2a00e768-fe46-11e4-8f58-8a474e44b883.png)

**Comment by deadok22** [comment]
Hi @kanga-roo,

as you can see from your console output, ```fact:fac/1``` is undefined. Which means that either ```fact``` is not in your code path, or that module ```fact``` doesn't have a function ```fac/1``` defined and exported. 

So try running ```erl.exe``` in your project directory and call ```fact:module_info()``` to see what's going on.

By the way, your question is not a bug or a plugin issue, so this issue tracker is not the place to ask it. Please, use http://stackoverflow.com or something like that next time. Thanks.

**Comment by kanga-roo** [comment]
dear sergey, i sincerely appreciate your patience and guidance. thank you very much for your insights!
