### ISSUE TITLE
The selected directory is not a valid home for Erlang SDK

### ISSUE THREAD

**Issue by kanga-roo** [ignatov/intellij-erlang#602]
Dear Sergey, in desperation I have re-installed Erlang, IntelliJ and your SDK in the hope that I can set it up properly this time. I am trying
![erlangsdk](https://cloud.githubusercontent.com/assets/12368392/7743688/80af0900-ffe0-11e4-84d0-28a2085c78ce.png)
 to find a valid home for your Erlang SDK. Any clues? Many thanks!

**Comment by deadok22** [comment]
Hi @kanga-roo, your Erlang SDK path should point to a location where you have your Erlang/OTP installed. Your screenshot and description do not provide any information.

**Comment by kanga-roo** [comment]
i had been trying to install into IJ plugins with the warning message above. thank you once again for your guidance, sergey. it saved me significant time. very best wishes to you both as well as your team. i wish i could send you some warm oz sunshine, but it is pouring rain. hahaha best wishes!
