### ISSUE TITLE
Integers considered incorrect

### ISSUE THREAD

**Issue by Deepro** [ignatov/intellij-erlang#605]
Integers in base#value format are incorrect according to the plugin.

Though this is a correct way to define an integer in erlang: http://erlang.org/doc/reference_manual/data_types.html#id65014

As instance 32#ELEPHANT will be considered incorrect according to the plugin.

**Comment by telezhnaya** [comment]
The problem is deeper.
2#0123, 8#ABC will be considered correct (although there could be just numbers 0..1 and 0..7 respectively)
0#123, 1#123, 37#123, 99#123 will also be ok (base should be in range [2, 36])
