### ISSUE TITLE
erl files in ebin dir?

### ISSUE THREAD

**Issue by efooksman** [ignatov/intellij-erlang#608]
Hi, is there a reason for all erl files to be copied to ebin folder? this screws up lots of env scripts, grep-s and so on. Is there an option to prevent src->ebin copying and compiling straight from src?

**Comment by istocniks** [comment]
just to clarify, ebin folder = configured module output folder

**Comment by istocniks** [comment]
Found the code that does this in org.intellij.erlang.jps.builder.ErlangBuilder#addDebugInfo, is there a particular reason for doing this?

**Comment by deadok22** [comment]
I remember putting it there because the debugger module failed to find
sources otherwise. Probably, the same can be achieved by altering code path.

**Comment by efooksman** [comment]
Sergey, could you fix it - this is one of just couple if of major obstacles preventing me from completely switching to your otherwise great Erlang IDE. Thanks!
