### ISSUE TITLE
Single file compilation upon "save"

### ISSUE THREAD

**Issue by efooksman** [ignatov/intellij-erlang#609]
Hello. One of the most convenient features in Eclipse is background auto-compile on save. I use it all the time, I never have to think about compiling anything. I just save modified file, switch over to the shell window with my erlang app running and load changed file (it's already compiled and ready to be loaded by that time). Any plans to support something like this? Thanks.

**Comment by istocniks** [comment]
As I understand it's easy to compile everything on each save right now, you just need to activate the "Make project automatically" option in compiler options. 

![screen shot 2015-06-02 at 2 05 32 pm](https://cloud.githubusercontent.com/assets/1018740/7947217/918d8784-0930-11e5-9e39-a7d7eda05f75.png)

The big problem here is that currently Erlang compilation is not incremental, even if just a single line of code was changes the plugin builds a whole module which can take a very long time for us. 

I second that it would be awesome if you could address this.

**Comment by istocniks** [comment]
Before this update I could compile a single file in IDEA and reload it in erlang console, it reloaded a bunch of other files, but at least it worked, after this update I cannot reload any re-comiled file any more.

**Comment by deadok22** [comment]
Thank you, @istocniks, we'll take a look at it.

**Comment by istocniks** [comment]
Sorry, looks like the problem was on my side, looks like my comment wasn't posted

**Comment by deadok22** [comment]
Does it work fine now? What was the problem?

**Comment by istocniks** [comment]
It seems like my project didn't reference directly the files I was trying to re-compile, hence they did not reload. Obviously I did not notice this before.

I have another question though, I can see that all my files now are compiles into both normal and test output directories, but I don't have any test sources defined, why does it happen?

**Comment by deadok22** [comment]
We decided to always compile both tests and source due to this issue: https://github.com/ignatov/intellij-erlang/issues/513

IntelliJ's build system doesn't differentiate between test and production builds, so the only way to handle it was to compile both tests and production code at once. The thing is, modules for tests are compiled with -DTEST which may add some functionality used in unit tests. Also, we have no reliable way of telling whether your source code contains tests.

Let me know if you think there's a better way to go about it.

**Comment by istocniks** [comment]
I'm sure you know these things better than me, just was curious why this happened :) 
What would change if I'd add a test directory to my module? Will files there be compiled to test output directory only?

**Comment by deadok22** [comment]
Yes, files from test source roots are only compiled to tests output directory.

BTW, rebar does the same thing - it compiles production code to ebin, and both production and tests code to .eunit by default. Of course, it has the advantage of knowing whether to compile tests or not.

**Comment by istocniks** [comment]
Awesome, thanks for the explanation!

**Comment by deadok22** [comment]
Since you already use the latest version of the plugin, be careful - we don't have some erlang module dependency types covered yet - file inclusions, for example. So if you change anything in your headers, please hit 'Rebuild' instead of 'Make'. We'll have this covered in a couple of days.

**Comment by istocniks** [comment]
Will keep in mind, thanks again :)
