### ISSUE TITLE
-import in hrl file not respected 

### ISSUE THREAD

**Issue by xenolinguist** [ignatov/intellij-erlang#613]
To see this bug in a real project, check out https://github.com/xenolinguist/hoax

In `include/hoax.hrl` is the following line:
```erlang
-import(hoax, [mock/2, stub/3]).
```

Users of hoax will `include_lib` this hrl in their eunit test, like in `tests/hoax_tests.erl:6`
```erlang
-include_lib("hoax/include/hoax.hrl").
```

They can then use `hoax:mock/2` or `hoax:stub/3` without needing to specify the module, like in `tests/hoax_tests.erl:14`
```erlang
mock(hoax_test_module, ?expect(function_one, ?withArgs([1, 2]), ?andReturn(mocked_return_value))),
```

Unfortunately, the plugin doesn't respect the -import inside the hrl, and erroneously calls this an error, like in this screenshot.

![image](https://cloud.githubusercontent.com/assets/181127/8139638/c90ed40a-111a-11e5-8c1d-e7b5f37354fa.png)

**Comment by xenolinguist** [comment]
Interestingly, if I add the -import to the test file itself, and then delete it, the plugin seems to somehow 'remember' even after restarting IntelliJ.

**Comment by deadok22** [comment]
I cannot reproduce this.

I've checked out the project, opened ```tests/hoax_tests.erl:14``` and it's all good - no warnings, Ctrl+Click on ```mock/2``` calls navigates to ```hoax.erl:20``` which is correct.

Looks like I've fixed it in https://github.com/ignatov/intellij-erlang/commit/159e41b38e940a184f273930d8f3d72a8a7284fa - try updating.
