### ISSUE TITLE
Project SDK is not defined...

### ISSUE THREAD

**Issue by egorovd** [ignatov/intellij-erlang#614]
Hi, 

http://joxi.ru/a2XaL15czVkMAg

http://joxi.ru/E2pW6YGtqYpLmY

Tell me how it can be solved.

Thank you.

**Comment by deadok22** [comment]
Hi @egorovd,

Please let us know what your OS, Erlang, IDE, and plugin versions are.

Also please make sure that your Erlang installation is ok and it's binaries are executable by the IDE.

**Comment by egorovd** [comment]
Installation is ok.

Not problem run any erlang app.


OS

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty


Erlang 

from http://erlang-solutions.com :  1:17.5.3

cat /usr/lib/erlang/releases/RELEASES

[{release,"Erlang/OTP","17","6.4.1",
          [{kernel,"3.2","/usr/lib/erlang/lib/kernel-3.2"},
           {stdlib,"2.4","/usr/lib/erlang/lib/stdlib-2.4"},
           {sasl,"2.4.1","/usr/lib/erlang/lib/sasl-2.4.1"}],
          permanent}].



iDE
http://joxi.ru/EA4ngJDSzjPYmb

plugin
http://joxi.ru/l2ZnZ7WS5OzR2J

Thank you.

**Comment by NobbZ** [comment]
What does "which erl" tell you?

egorovd <notifications@github.com> schrieb am Di., 23.06.2015, 14:50:

**Comment by egorovd** [comment]
/usr/bin/erl

**Comment by deadok22** [comment]
@egorovd 

In your case the plugin runs the following to determine SDK version:
```bash
/usr/lib/erlang/bin/erl -noshell -eval 'io:format("~s~n~s",[erlang:system_info(otp_release),erlang:system_info(version)]),erlang:halt().'
```

Unfortunately, there was no logging of the output until the latest commit. Could you please run the command above in your terminal and share what the output is?

**Comment by egorovd** [comment]
No problem...

$  /usr/lib/erlang/bin/erl -noshell -eval 'io:format("~s~n~s",[erlang:system_info(otp_release),erlang:system_info(version)]),erlang:halt().'
consulting .erlang in "/home/denis"
Now in:"/home/denis"
17
6.4.1

or screenshot

http://joxi.ru/LmGqbYkc8zvxAl

**Comment by deadok22** [comment]
There actually is a problem =)

I didn't expect these lines
```
consulting .erlang in "/home/denis"
Now in:"/home/denis"
```
to appear.

I'll fix it, thank you.

**Comment by egorovd** [comment]
Super! :)

Thank you.
