### ISSUE TITLE
IntelliJ IDEA 15 (EAP) support

### ISSUE THREAD

**Issue by magicgoose** [ignatov/intellij-erlang#615]
The new IntelliJ IDEA 15 is a special release, as it finally fixes the broken font rendering. (https://youtrack.jetbrains.com/issue/IDEA-117324) But right now the plugin is not compatible with IntelliJ IDEA 15 (EAP). It would be great to support it.

**Comment by oawoyemi** [comment]
+1 this would be useful even in EAP

**Comment by deadok22** [comment]
Hey guys,

I've posted an IntelliJ 15 EAP compatible pre-release build at https://github.com/ignatov/intellij-erlang/releases

**Comment by oawoyemi** [comment]
Awesome - I'll check it out

**Comment by michaelklishin** [comment]
It would be great to see IDEA 15 support now that it is out.
