### ISSUE TITLE
"Show Line Numbers" option hasn't been remembered

### ISSUE THREAD

**Issue by Micheus** [ignatov/intellij-erlang#617]
Every time I start the application I need to use the menu View->Active Editor->Show Line Numbers in order to see them.

Intellij IDEA: 14.1.3
Erlang plugin: 0.5.11

**Comment by ignatov** [comment]
Please enable File | Settings | Editor | General | Appearance | Show line numbers.

**Comment by Micheus** [comment]
Thanks. That do the trick for all files opened.
I used to show them only for that files I was working/debugging, that is why I thought it could remember only for them.

**Comment by ignatov** [comment]
How IDEA can determine them? :)

**Comment by Micheus** [comment]
I imagined it could add that information to some project file it create, maybe in a file like workspace.xml where the Favourites are stored. ;)
