### ISSUE TITLE
Bookmarks by file

### ISSUE THREAD

**Issue by Micheus** [ignatov/intellij-erlang#618]
Couldn't the bookmark feature be implemented by file?
By now if I use a combination already used in a file (e.g. CTRL+1) in another file, the first one is lose.

**Comment by ignatov** [comment]
Hi, you can use bookmarks with letters: https://www.jetbrains.com/idea/help/managing-bookmarks.html#createNumbered

**Comment by ignatov** [comment]
BTW, looks like a platform feature request, please submit a new one: https://youtrack.jetbrains.com/issues/IDEA#newissue

**Comment by Micheus** [comment]
Sorry. That was embarrassing.
It should be obvious I have to report this to the Intelij IDEA guys.
