### ISSUE TITLE
Can't see the result of eunit test

### ISSUE THREAD

**Issue by CorcovadoMing** [ignatov/intellij-erlang#629]
I got the following message when starting a fail test:
```
Test runner terminated. Reason: {error,badarg,
                                 [{erlang,binary_to_list,[[<<>>]],[]},
                                  {eunit_teamcity,get_test_failed_details,1,
                                   []},
                                  {eunit_teamcity,error_test_attributes,1,[]},
                                  {eunit_teamcity,end_test,2,[]},
                                  {eunit_listener,call,3,
                                   [{file,"eunit_listener.erl"},{line,131}]},
                                  {eunit_listener,group_loop,4,
                                   [{file,"eunit_listener.erl"},{line,92}]},
                                  {eunit_listener,init,2,
                                   [{file,"eunit_listener.erl"},{line,58}]}]}

=ERROR REPORT==== 17-Jul-2015::07:28:08 ===
Error in process <0.30.0> with exit value:
{badarg,[{erlang,binary_to_list,[[<<>>]],[]},
         {eunit_teamcity,get_test_failed_details,1,[]},
         {eunit_teamcity,error_test_attributes,1,[]},
         {eunit_teamcity,end_test,2,[]},
         {eunit_listener,call,3,[{file,"eunit_listener.erl"},{line,131}]},
         {eunit_listener,group_loop,4,[{file,"eunit_listener.erl"},{line,92}]},
         {eunit_listener,init,2,[{file,"eunit_listener.erl"},{line,58}]}]}
```
There are no any information about which line of the test fail

I found the default test command is `"eunit:test([XXX], [{report, {eunit_teamcity,[]}}, {no_tty, true}])."`

it seems that it default redirect the report of test to enit_teamcity listener?
How could I configure the setting to not to redirect the report, just show up in the intellij console?
( I want to just execute the command: `"eunit:test([XXX])."`)

**Comment by deadok22** [comment]
Hi @CorcovadoMing!

Yes, it does redirect reports to [eunit_teamcity](https://github.com/deadok22/eunit_teamcity_reports) listener. We then parse the output in order to show the test runner UI. 

So it's not your test that's failing, but our eunit_teamcity module. Would you mind submitting a pull request to [eunit_teamcity](https://github.com/deadok22/eunit_teamcity_reports) to fix this?

**Comment by deadok22** [comment]
@CorcovadoMing if you're not going to fix it yourself, please, tell me what's your Erlang version. It would also be great to get a short code sample which allows to reproduce the problem. Thanks!

**Comment by CorcovadoMing** [comment]
@deadok22 
I'm just starting learning Erlang, so I'm afraid that I can't fix the code
but you've mentioned the Erlang version, so I download the version OTP 17.0 ( I'm currently using 18 ), and all the function seems to work perfectly!

**Comment by deadok22** [comment]
Good, then I'll try to figure out what's going wrong with 18th release.

BTW, as you can see from the trace you shared, the problem is that the eunit_teamcity module calls ```{erlang,binary_to_list,[[<<>>]],[]}```. But ```erlang:binary_to_list/1``` is supposed to be called with a binary as an argument.

**Comment by deadok22** [comment]
Thank you, @CorcovadoMing!

**Comment by CorcovadoMing** [comment]
@deadok22 Thank you for the fix! :)

**Comment by deadok22** [comment]
You're welcome. I'll publish a fresh build as soon as it's ready.

**Comment by deadok22** [comment]
@CorcovadoMing, feel free to grab a new build from https://github.com/ignatov/intellij-erlang/releases

**Comment by CorcovadoMing** [comment]
@deadok22 It works great !!!! Thanks :)
