### ISSUE TITLE
undefined callback function format_status/2 for gen_servers

### ISSUE THREAD

**Issue by brigadier** [ignatov/intellij-erlang#644]
The plugin shows this warning for every gen_server module: `undefined callback function format_status/2`.
This function is optional for gen_server, has default implementation, and is almost never implemented in callback modules.

From the docs on gen_server:
"This callback is optional, so callback modules need not export it. The gen_server module provides a default implementation of this function that returns the callback module state."

upd: `-optional_callbacks([])` is a new directive introduced in 18.0, for example `-optional_callbacks([format_status/2]).`, It means the callbacks have default implementation in the behaviour module.

**Comment by deadok22** [comment]
@telezhnaya, please, take a look - it should be easy to fix it now since we have https://github.com/ignatov/intellij-erlang/pull/656 merged in.
