### ISSUE TITLE
How to set indent like vimerl?

### ISSUE THREAD

**Issue by dcy** [ignatov/intellij-erlang#664]
I used vim+vimerl, https://github.com/jimenezrick/vimerl
And i want to use intellij-erlang now, but the indent is not like vimerl's.

**Comment by deadok22** [comment]
We don't have presets for vimerl's style or any other - you can try to configure formatting options in your IDE settings to make it somewhat similar to vimerl's formatting.

If you need your code formatted exactly the way vimerl formats it, you can try using vimerl itself to do it.

If you're into hacking your IDE, take a look at https://github.com/ignatov/intellij-erlang/blob/master/src/org/intellij/erlang/actions/ErlangEmacsFormatAction.java to see how the same action for Emacs is implemented. You can also try using a built-in IDE scripting console (see https://gist.github.com/gregsh/b7ef2e4ebbc4c4c11ee9 and https://gist.github.com/AMPivovarov/a73e3a6057b6e06a3712 for script examples)

**Comment by dcy** [comment]
Thanks!
