### ISSUE TITLE
Resolving of functions with -include() attribute does not work properly

### ISSUE THREAD

**Issue by telezhnaya** [ignatov/intellij-erlang#676]
File `my_lib.hrl`:

``` erlang
process_info(A, B, C) -> ok.
```

File `main.erl`:

``` erlang
-module(main).
-include("my_lib.hrl").
 foo() -> process_info<caret>().
```

I try to resolve this function. There is no function with zero arity, so I should get all possible variants. 
I get 2 variants from standard library. But there should be 3 variants - from `my_lib` header also.

**Comment by NobbZ** [comment]
Does this even compile when you do it by hand? AFAIK -include wants a
symbol, not a filename.

telezhnaya <notifications@github.com> schrieb am Mo., 24.08.2015, 10:00:

**Comment by telezhnaya** [comment]
I have updated my comment.
Of course, it does not compile, even now. Because there is no function `process_info/0`.
But it is great if IDE will help us to choose from all possible variants of this function.

**Comment by kvakvs** [comment]
Additional notes: Could not reproduce in 2019. `process_info/3` is in the completions list

**Comment by telezhnaya** [comment]
@kvakvs thank you, let's close this issue then
