### ISSUE TITLE
Statement autocompletion doesn't work any more

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#683]
IDEA 14.1.5, Erlang 4825e15

Not sure when exactly it happened, but I was able to type 
`case A of <enter>` 
before and the plugin would automatically add 
`end,` 
to the end of the statement.
This doesn't work any more.

**Comment by deadok22** [comment]
Hi @istocniks,

Please share a code snippet so that I can reproduce the issue.

In the following example 'end' is added just as it should:
```erlang
foo() ->
  case A of<caret>
```

I hardly believe it doesn't work at all, as we have a bunch of tests checking just that: https://github.com/ignatov/intellij-erlang/tree/master/testData/autotemplates

**Comment by istocniks** [comment]
That's how it works for me
http://cl.ly/image/2n3i3L033H1e

**Comment by deadok22** [comment]
In your case there already is a matching 'end' - that's why it doesn't add it =)

**Comment by istocniks** [comment]
Few other examples
http://cl.ly/image/000h0g180h0c
http://cl.ly/image/1u270S1r2C3j

**Comment by deadok22** [comment]
Do you have "Editor" -> "General" -> "Smart Keys" -> "Enter" -> "Insert pair '}'" checkbox set?

**Comment by istocniks** [comment]
http://cl.ly/image/3F3O262L2m0e

**Comment by deadok22** [comment]
Have you installed any other plugins recently?

**Comment by istocniks** [comment]
Not really.... here's the list of all my plugins
http://cl.ly/image/0H0707461H0a

**Comment by deadok22** [comment]
It's Perl5 Support messing things up. 

The file to blame: https://github.com/hurricup/Perl5-IDEA/commits/04a80f9e475165a88fa6d42cf40f4f3397347a84/src/com/perl5/lang/perl/idea/editor/PerlEnterHandlerDelegate.java

It's current version looks good, but before it was returning Result.DefaultSkipIndent from preprocessEnter, which caused the trouble. 

So either wait for Perl5 Support to update, or build it from source. Cheers!

**Comment by istocniks** [comment]
Awesome! Thanks for the fast and detailed response
