### ISSUE TITLE
Erlang plugin hangs my IntelliJ when trying to open the popup on the root of my project

### ISSUE THREAD

**Issue by ringods** [ignatov/intellij-erlang#684]
I have a NON-erlang project, but I have the Erlang plugin installed in my IntelliJ. When I try to open the popup menu on the root folder of my project, my IntelliJ becomes unresponsive. Screen redraws happen, but I can select anything, in the tree nor switch tabs.

Checking the logs on my Mac, I see a thread dump file being generated every 5 seconds, with a clear pointer to this plugin as almost the only active thread.

https://gist.github.com/ringods/a60b6f3e5c61e5f08765

**Comment by deadok22** [comment]
Hi @ringods!

Looks like it's a duplicate of https://github.com/ignatov/intellij-erlang/issues/576.

Please try a build from https://github.com/ignatov/intellij-erlang/releases, and let me know if the issue's still there.

**Comment by ringods** [comment]
@deadok22 I'll try tomorrow. Which build is more recent than v0.5.11 which I have currently? I don't see Git tags beyond 0.5.9.

**Comment by deadok22** [comment]
Just grab the most recent one. Right now it's https://github.com/ignatov/intellij-erlang/releases/tag/%23778.

**Comment by ringods** [comment]
@deadok22 yep, this seems to have resolved the issue.
