### ISSUE TITLE
Can't add Erlang SDK 

### ISSUE THREAD

**Issue by twanvanderschoot** [ignatov/intellij-erlang#686]
Hi,

A silly problem. On Mac OSX the Erlang SDK is standard installed in /usr/local/lib/erlang.  /usr is a _hidden_ directory and won't show up in the file dialog box when configuring an ErlangSDK and this is the only way to add a path to the SDK.  Usually Mac OSX file dialog boxes have a nifty feature (enabled?): with the file dialog opened, keying in `/`  opens an extra sheet allowing the user to enter _any_ path, including hidden paths.

This feature is _not_ enabled in the file dialog box when configuring an SDK for Erlang.  I don't know whether it is an issue with IntelliJ or the plugin. In any case, in other file dialog boxes opened by IntelliJ the feature _is_ enabled.  

If it is the case that you must/can set this feature in the plugin code, please do so at the earliest possible moment.  

Of course there is a workaround:  make a symbolic link in your home directory:  

    sudo ln -s /usr/local/lib/erlang  Erlang-SDK

But this is, of course, really ugly in an otherwise great plugin.

/Twan

**Comment by deadok22** [comment]
It's already fixed in IntelliJ 15.

For now, you can set ```ide.mac.file.chooser.native``` property to ```false``` either via IntelliJ Registry action, or in IntelliJ's ```.vmoptions``` file by appending the following line: ```-Dide.mac.file.chooser.native=false```.

**Comment by twanvanderschoot** [comment]
Cool!

Thanks for the quick response!

/Twan

--
Twan van der Schoot
TWAN.COM
m: +31 6 15052501
e: twan@twan.com
w: www.twan.com
