### ISSUE TITLE
Rebar setup on Windows

### ISSUE THREAD

**Issue by davidhopkins** [ignatov/intellij-erlang#687]
On Windows and having a very similar problem to the one described in #470. Am getting:

> N/A: Error: 'escript.exe' is not recognized as an internal or external command,

when pointing the rebar path to rebar.cmd. Rebar is appears to be on the PATH as I can run it fine from a terminal. Anything else I could try?

**Comment by deadok22** [comment]
The thing is, you should point your rebar path to rebar itself, not to rebar.cmd. Hence, the error message.

**Comment by davidhopkins** [comment]
This is exactly the opposite of what was said here:

https://github.com/ignatov/intellij-erlang/issues/470#issuecomment-42101454

In either case I've tried just setting it to the directory and it also does not work. I don't get any errors but I am unable to proceed with the setup dialogue. 

Thanks

**Comment by deadok22** [comment]
Yes, it is the opposite of what the comment says. But that comment was made on May 3rd 2014 - things change =)

Please, install the plugin using the latest release from https://github.com/ignatov/intellij-erlang/releases, and try what I suggested earlier.

I'm sorry I forgot to mention you need an updated version of the plugin.

**Comment by deadok22** [comment]
So is ```C:\Users\gbhopkida\projects\rebar``` a directory, or is it a rebar binary?

**Comment by davidhopkins** [comment]
~/projects/rebar $ pwd
    /cygdrive/c/Users/gbhopkida/projects/rebar
    ~/projects/rebar $ ./rebar --version
    rebar 2.6.1 18 20151021_135843 git 2.6.1-6-gb870e06

**Comment by davidhopkins** [comment]
Sorry I misunderstood you slightly. Essentially I have tried all three of the following:

1. C:\Users\gbhopkida\projects\rebar
2. C:\Users\gbhopkida\projects\rebar\rebar
3. C:\Users\gbhopkida\projects\rebar\rebar.cmd

Only the third one gives me any output the others just appear to do nothing.

**Comment by deadok22** [comment]
The plugin does runs the following to get rebar version:
```
escript.exe rebar_path --version
```
Is escript.exe on your PATH?

**Comment by davidhopkins** [comment]
I assume you're talking about Windows PATH in which case yes it is on it. I can run it from cmd line ok.

    ~ $ escript.exe "C:\Users\gbhopkida\projects\rebar\rebar" --version
    rebar 2.6.1 18 20151021_135843 git 2.6.1-6-gb870e06

The only strange thing is I cannot run it using the cygwin path - i do not think this should matter for IntelliJ however

    ~ $ escript.exe /cygdrive/c/Users/gbhopkida/projects/rebar/rebar --version
    escript: Failed to open file: /cygdrive/c/Users/gbhopkida/projects/rebar/rebar
    ~ $ ls -l /cygdrive/c/Users/gbhopkida/projects/rebar/rebar
    -rwxrwxr-x+ 1 GBHopkiDa Domain Users 203923 Oct 21 14:58 /cygdrive/c/Users/gbhopkida/projects/rebar/rebar

**Comment by deadok22** [comment]
@davidhopkins could you please do the following:
1. Open "Tools" -> "IDE Scripting Console"
2. Choose "Groovy" as your scripting language
3. Paste the script below in the editor
4. Select the pasted script in your editor, and hit "Ctrl+Enter"
5. Share the scripts' output

```groovy
import com.intellij.ide.plugins.PluginManager;
import com.intellij.openapi.extensions.PluginId;

plugin = PluginManager.getPlugin(PluginId.findId("org.jetbrains.erlang"))
cl = plugin.getPluginClassLoader()

sdk = cl.loadClass("org.intellij.erlang.jps.model.JpsErlangSdkType")
epu = cl.loadClass("org.intellij.erlang.utils.ExtProcessUtil")

escript = sdk.getExecutableFileName(sdk.SCRIPT_INTERPRETER);
rebar = "C:\Users\gbhopkida\projects\rebar\rebar"

IDE.print("File exists: " + new File(rebar).exists())

output = epu.execAndGetFirstLine(3000, escript, rebar, "--version");

IDE.print("OUT: " + output.getStdOut())
IDE.print("ERR: " + output.getStdErr())
```

**Comment by davidhopkins** [comment]
I had to modify the path to be 
`rebar = "C:\\Users\\gbhopkida\\projects\\rebar\\rebar"`
Then when I ran it I got the error: 
`MissingPropertyException: No such property: SCRIPT_INTERPRETER for class: org.intellij.erlang.jps.model.JpsErlangSdkType`
I also tried running it with the official version. This then gave the error: 
`ClassNotFoundException: org.intellij.erlang.jps.model.JpsErlangSdkType PluginClassLoader[org.jetbrains.erlang, 0.5.11]`

**Comment by deadok22** [comment]
The version plugin repository version doesn't have this class in it.

Well, it sounds weird that SCRIPT_INTERPRETER property was not found. Try the following, then:
```groovy
import com.intellij.ide.plugins.PluginManager;
import com.intellij.openapi.extensions.PluginId;

plugin = PluginManager.getPlugin(PluginId.findId("org.jetbrains.erlang"))
cl = plugin.getPluginClassLoader()

epu = cl.loadClass("org.intellij.erlang.utils.ExtProcessUtil")

escript = "escript.exe"
rebar = "C:\\Users\\gbhopkida\\projects\\rebar\\rebar"

IDE.print("File exists: " + new File(rebar).exists())

output = epu.execAndGetFirstLine(3000, escript, rebar, "--version");

IDE.print("OUT: " + output.getStdOut())
IDE.print("ERR: " + output.getStdErr())
```

**Comment by davidhopkins** [comment]
That produces

    File exists: true
    OUT: rebar 2.6.1 18 20151021_135843 git 2.6.1-6-gb870e06
    ERR: 
    => null

**Comment by deadok22** [comment]
Well, that's exactly what the plugin expects to get.

Which file did you point to when you installed the plugin from https://github.com/ignatov/intellij-erlang/releases? You should have pointed to a .zip file, and not to jar(s).

Otherwise, it would be great to get logs from you. ("Help" -> "Show Log in Explorer". I'm only interested in idea.log file)

**Comment by davidhopkins** [comment]
I used the jar...I just tried it again with the zip and it works fine. SORRY!

**Comment by deadok22** [comment]
I'm glad it works now. Happy hacking! =)
