### ISSUE TITLE
Incorrect multiline comment behavior

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#688]
Please look at what happens when I want to split a comment into two lines by pushing Enter in the middle of it:
![screen shot 2015-10-30 at 3 19 34 pm](https://cloud.githubusercontent.com/assets/1018740/10859330/cdac4cd2-7f19-11e5-9416-9b4533b823a2.png)
![screen shot 2015-10-30 at 3 21 23 pm](https://cloud.githubusercontent.com/assets/1018740/10859348/f09b76d2-7f19-11e5-8cc4-c3f3f27758a1.png)

**Comment by deadok22** [comment]
Thank you @istocniks, it was very inconvenient, indeed.
