### ISSUE TITLE
Update for WebStorm 11/latest IntelliJ

### ISSUE THREAD

**Issue by sdebnath** [ignatov/intellij-erlang#689]
Just upgraded to WebStorm 11 and realized that the Erlang plugin is now incompatible with the new release. Any chance someone can get it updated so we can resume our erlang work with this awesome plugin?

Thanks.

**Comment by deadok22** [comment]
Have you tried the latest build from https://github.com/ignatov/intellij-erlang/releases ?

**Comment by sdebnath** [comment]
That I hadn't! Works like a charm - thank you!
