### ISSUE TITLE
Erlang plugin breaks IDEA automatic VCS file status refresh

### ISSUE THREAD

**Issue by tuscland** [ignatov/intellij-erlang#693]
Hello,

When the Erlang plugin is enabled (IDEA 14 or 15), as soon as a file is modified, its color changes to light-brown instead of blue (when it is managed under VCS).

I have to manually choose Refresh File Status to actually see the changes in the Editor. As soon as I type text in the Erlang file, its color reverts to light-brown and the VCS changes indicators are lost.

Best,
Camille

**Comment by deadok22** [comment]
Hi @tuscland,

I'm not sure I understand what's happening - could you share some screenshots?

**Comment by tuscland** [comment]
Under normal operation the VCS changes look like this:

<img width="502" alt="sc1" src="https://cloud.githubusercontent.com/assets/556316/10964351/fdca8924-83a6-11e5-9551-3a319c5d5ae8.png">

And the file name is blue:

<img width="138" alt="sc2" src="https://cloud.githubusercontent.com/assets/556316/10964367/0d54b9f0-83a7-11e5-9b6c-619fe13e96f1.png">

But with Erlang plugin activated, when I change a file, VCS changes are lost:

<img width="473" alt="sc3" src="https://cloud.githubusercontent.com/assets/556316/10964382/21ec6bec-83a7-11e5-94e6-49d54f85fc56.png">

And the file name becomes light-brown:

<img width="149" alt="sc4" src="https://cloud.githubusercontent.com/assets/556316/10964395/2d8588a8-83a7-11e5-912f-98abafbee98e.png">

Finally, when I choose "Refresh File Status" from the VCS menu, the VCS changes come back to normal (until next edit):

<img width="481" alt="sc5" src="https://cloud.githubusercontent.com/assets/556316/10964404/40459f3c-83a7-11e5-8518-0d01616fa463.png">

A representative from JetBrains support helped me identify the Erlang plugin as the cause of this problem.

**Comment by deadok22** [comment]
It looks like the file you're editing is in VCS ignore list.

Please, check ```Settings -> Version Control -> Ignored Files``` to see if that's the case.

**Comment by tuscland** [comment]
Damn, that was the culprit; it's embarrassing.
Thank you so much for finding this problem!
