### ISSUE TITLE
Can not set Eunit working directory

### ISSUE THREAD

**Issue by Startigers** [ignatov/intellij-erlang#694]
When I set a path in the run configuration of an **Eunit** test and reopen the configuration then the working directory is empty again. The directory is not saved.
In contrast the working directory is saved correctly in case of an Erlang Application. There is no problem.

I use pre-release #835 / IDEA 15.

**Comment by deadok22** [comment]
Thank you, @Startigers. I'll publish a fresh build as soon as it's built.

**Comment by deadok22** [comment]
A fresh build is available at https://github.com/ignatov/intellij-erlang/releases

**Comment by Startigers** [comment]
Great, thank you. I tested it and now it works.
