### ISSUE TITLE
Add option (in UI) to enable HiPE (native) compilation

### ISSUE THREAD

**Issue by magicgoose** [ignatov/intellij-erlang#699]
it's as simple as adding `native` atom to compile options. For example, `c("src/my_module", [native]).`

**Comment by deadok22** [comment]
Looks like there won't be any trouble adding this flag. We should simply add ```+native``` to our ```erlc``` arguments list.

I wonder if it's compatible with ```+debug_info``` flag. 

May be we should consider allowing to add custom compiler flags instead.

**Comment by magicgoose** [comment]
> May be we should consider allowing to add custom compiler flags instead.

May be.

**Comment by deadok22** [comment]
Custom compiler arguments can be added in 'Settings' -> 'Build, Execution, Deployment' -> 'Compiler' -> 'Erlang Compiler'. 

The latest plugin build is available [here](https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Erlang&tab=projectOverview)
