### ISSUE TITLE
import a project from eclipse, include not work

### ISSUE THREAD

**Issue by hanhaoxian** [ignatov/intellij-erlang#705]
I've import a existing project from eclipse, Intellij both 14 and 15 version, but the -include() not work.

I put *.hrl to directory name include, I must write a complete path so that it works.

I found someone resolve by mark directory as Include Root, but I never found it.

**Comment by deadok22** [comment]
Hi @hanhaoxian,

If you import your project properly, the plugin will ask you to mark the directories named 'include' as include directories. So if it doesn't do so, you must have imported your project in some unexpected way.

In order to help you, I'm going to need to know some more about your project. What build system does it use? What's it's directory structure?

In any case, you can mark your directories as include roots via a context menu action on your directory, or in project structure view.

**Comment by hanhaoxian** [comment]
It can be like this when eclipse project :
![image](https://cloud.githubusercontent.com/assets/3611408/11425806/8ecee662-9492-11e5-81ed-29e17aff344b.png)

after import, the structure view like this:
![image](https://cloud.githubusercontent.com/assets/3611408/11425967/b15dd9ee-9493-11e5-9566-4f92f9a9fbcc.png)

and what I can't set as include roots is because there is no choice...
![image](https://cloud.githubusercontent.com/assets/3611408/11426010/f9ab4ea2-9493-11e5-8dfc-b6eea6c8154a.png)


by the way, my project is not managed by rebar,

**Comment by deadok22** [comment]
It looks like import from eclipse is not doing it's best here. I could take a look at it, if you shared an eclipse project with me.

Meanwhile, what I suggest is not using import from eclipse, but creating a project from existing sources, selecting an Erlang SDK while creating it, then marking your src and include roots as include and source roots, respectively.

**Comment by hanhaoxian** [comment]
oh, thank you. It works.
I've new the Erlang project, and add all file and directory after it, so the include root can be choose.
It seem after importing the eclipse project, the plugin not regard it as Erlang project.

**Comment by deadok22** [comment]
That was my guess =)

Could you please set up a simple eclipse project for me so that I could see what's happening there, and may be fixed it?

**Comment by hanhaoxian** [comment]
Of cause, but It should be tomorrow when I'm in the company, I remote company's pc by vpn just now, it always lost connection, it would cost much time.

**Comment by hanhaoxian** [comment]
@deadok22 I've new the project for test, clone from https://github.com/hanhaoxian/test_server.git

**Comment by deadok22** [comment]
Thank you, @hanhaoxian. I'll take a look at it.
