### ISSUE TITLE
Parser fails to recognize a variable

### ISSUE THREAD

**Issue by saleyn** [ignatov/intellij-erlang#718]
The variable `Reply` is not recognized by the plugin's parser:

![image](https://cloud.githubusercontent.com/assets/272543/12572718/cf0c415c-c3bd-11e5-984d-68cfe12d6b76.png)

**Comment by wmorrison1967** [comment]
Unless I am not understanding but I think that each case statement section is separate so variables declared in one cannot be used by the other.  You need to set Reply before the case statement.

**Comment by saleyn** [comment]
That is not the case, since `Reply` is set in every branch of the case statement, immediately following that case statement the `Reply` variable is considered bound.  This is not so **only** when the variable is bound in *some* **but not all** branches of the case.  You can try to compile this code in Erlang, and see that it works fine, yet the Intellij plugin doesn't understand it.

**Comment by wmorrison1967** [comment]
This I did not know.

**Comment by ignatov** [comment]
Relates to #737

**Comment by kvakvs** [comment]
This is a duplicate of #819
Grouping everything under one most recent issue
Thank you for reporting
