### ISSUE TITLE
Erlang Term Files Error when the files named *.cfg or other suffix whitout .config

### ISSUE THREAD

**Issue by iclodq** [ignatov/intellij-erlang#721]
![feo8g5w2 zi42 qpu 2jjip](https://cloud.githubusercontent.com/assets/14278872/12681737/055d2b74-c6eb-11e5-9f15-2cd67d9534d5.png)
![wasx1ba mavth wi6 f n1](https://cloud.githubusercontent.com/assets/14278872/12681741/0970c89c-c6eb-11e5-8e40-884b602dcc0a.png)

Idea version 15.0.3
erlang plugin version 0.6.837  
And I know  version 719 works well.

**Comment by deadok22** [comment]
Thank you, @iclodq!

It is fixed now. You can find a new build at https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Erlang&tab=projectOverview in 'Artifacts' dropdown.

Cheers!

**Comment by iclodq** [comment]
Thank you for your good job! @deadok22
