### ISSUE TITLE
Erlang project using erlc

### ISSUE THREAD

**Issue by wmorrison1967** [ignatov/intellij-erlang#723]
Hello,
      I need a some assistance with configure intelliJ to use erlc to compile my project but also accepting compile directives such as LAGER and DNO_EXT_LIB.

I would like to execute:
 erlc -v -DLAGER=true -DNO_EXT_LIB -I etc... 

Regards,
Will

**Comment by deadok22** [comment]
Custom compiler arguments can be added in 'Settings' -> 'Build, Execution, Deployment' -> 'Compiler' -> 'Erlang Compiler'. 

The latest plugin build is available [here](https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Erlang&tab=projectOverview)
