### ISSUE TITLE
Intellij 16 support

### ISSUE THREAD

**Issue by ptxmac** [ignatov/intellij-erlang#725]
IDEA 16 just entered public preview, and plans for when a new version of the erlang plugin will be ready?

**Comment by ignatov** [comment]
I'm going to prepare a build soon. If you'd like you can create a PR request. It's easy to update the platform version in gradle.properties.
The list of build – https://www.jetbrains.com/intellij-repository/releases

**Comment by os97673** [comment]
@ignatov I believe this one can be close ;)
