### ISSUE TITLE
Failure to identify behavior module

### ISSUE THREAD

**Issue by saleyn** [ignatov/intellij-erlang#730]
It seem that when searching for a behavior module, the plug in is looking for the behavior_info/1 function.

![image](https://cloud.githubusercontent.com/assets/272543/13924945/bb177f98-ef5c-11e5-9eef-43b1dfd2fa14.jpg)

However, in more recent Erlang releases the behaviors are implemented using for following style callbacks:
```
-callback init(Cfg :: #stratcfg{}) ->
  {ok, State::term()} | {error, string()}.

-callback format_state(State::term()) -> list().

-optional_callbacks([format_status/1]).
```

**Comment by deadok22** [comment]
@saleyn what does the warning say?

I've tried to reproduce, and it works just fine. Also, the code building behaviour indices explicitly looks for callback declarations.

Please, share a small project where this is reproducible. By the way, what's your plugin and IntelliJ version?

**Comment by saleyn** [comment]
Sorry, my bad - the behavior didn't have some callbacks implemented, and that was the reason for the errors.
