### ISSUE TITLE
Running a project compiled with rebar3.

### ISSUE THREAD

**Issue by pviotti** [ignatov/intellij-erlang#731]
Hello!

I'm trying to run a project which I compile with rebar3.
The project itself and its dependencies get compiled into `/path/to/my/project/_build/default/lib`.

Is there a way to instruct intellij to automatically look for dependencies in that folder rather than adding all dependencies' beam paths one by one in the `Flags for erl:` textbox as `-pa` items?

I tried adding `-pa /path/to/my/project/_build/default/lib/*/ebin` but the star trick doesn't work...

Version: Intellij 2016.1, Erlang plugin 0.7.876, Linux

**Comment by zyuyou** [comment]
@pviotti You using `Erlang Console` or `Erlang Application`? 
There are two methods for your problem: one is that set the app's output path to `/path/to/my/project/_build/default/lib/*/ebin`, another one is that use [the test version](https://github.com/zyuyou/intellij-erlang-rebar3-test-distributions) which I'm working on for supporting `Rebar3`, but the other features maybe not the newest.

**Comment by pviotti** [comment]
I'm using `Erlang Application` - (just tried `Erlang Console` as well, but can't make it work..)
Ok, thanks, I'll probably give a try to that test version in the next days

**Comment by marco-m** [comment]
Suggest closing this issue since it is a duplicate of https://github.com/ignatov/intellij-erlang/issues/704

**Comment by marco-m** [comment]
Again, Suggest closing this issue since it is a duplicate of #704.

**Comment by pviotti** [comment]
Ok - closing as duplicate of #704

**Comment by marco-m** [comment]
And if you follow #704, you will see that we actually have now enough rebar3 support to actually use it :-)
