### ISSUE TITLE
Defining a callback named "receive" causes infinite re-indexing

### ISSUE THREAD

**Issue by KallDrexx** [ignatov/intellij-erlang#732]
As a newbie to Erlang I decided to define a callback for a function called "receive", stupidly not thinking that this would conflict with the receive keyword/system function.  While it didn't work I noticed that defining this callback caused Intellij to go into an endless indexing loop until I deleted the line.

To reproduce, just add the following to the top of any module:
`-callback receive() -> 'ok'.`

**Comment by deadok22** [comment]
Thank you for reporting, @KallDrexx. It's fixed now.
