### ISSUE TITLE
Modify the erlang grammars support

### ISSUE THREAD

**Issue by haoxianhan** [ignatov/intellij-erlang#737]
for the old project, piece of code following would compile success but plugins regard it as error.
Is there any way to modify the grammars config ???

```
    Type  = 1,
    Type1 = 0,
    case Type of
        1 ->
            Times = 1;
        _ ->
            Times = 0
    end,
    case Type1 of
        1 ->
            io:format("Time ~p~n", [Times]);
        _ ->
            skip
    end,

```

![image](https://cloud.githubusercontent.com/assets/3611408/15285091/d7db1d72-1b87-11e6-894b-7b30ac5a75d4.png)

**Comment by kvakvs** [comment]
Closing as duplicate of #819
Thanks for reporting
