### ISSUE TITLE
indentation change?

### ISSUE THREAD

**Issue by benoitc** [ignatov/intellij-erlang#738]
Right now the editor does the following when I put on the next line:

```erlang
case ets:new(?TAB, [set, named_table, public, 
  {read_concurrency, true}, {write_concurrency, true}]) of
```

But I would like to have like on emacs or vim the next line starting after the `[`:

```erlang
case ets:new(?TAB, [set, named_table, public, 
                    {read_concurrency, true}, {write_concurrency, true}]) of
```

Is this possible?

**Comment by ignatov** [comment]
OK, will see what we can do with it.

**Comment by benoitc** [comment]
thanks!

**Comment by ignatov** [comment]
Please try **File | Settings | Editor | Code Style | Erlang** > **Alignment | Blocks (fun...end, etc)**.

**Comment by benoitc** [comment]
@ignatov unfortunately it doesn't work :( it aligns it with the block

**Comment by ignatov** [comment]
Please share a peace of code for reproducing. Also attach your formatter setting.

**Comment by benoitc** [comment]
@ignatov well you can try with the code above, type "enter" at the end of public and yyou will see the results. One another case is the following (posted on slack):

I have:
```erlang
-export([system_continue/3, 
  system_terminate/4,
  system_code_change/4]).
```

But I would like: 
```erlang
-export([system_continue/3,
         system_terminate/4,
         system_code_change/4]).
```

At leas this what I have on emacs or vim :) This is the only part i'm missing currently on intelli :)

**Comment by ignatov** [comment]
What does it mean `type "enter" at the end of public`?

**Comment by benoitc** [comment]
i typed the key "enter" :)

**Comment by ignatov** [comment]
Please specify position.

**Comment by benoitc** [comment]
hrm like the example above show this was `public,` in the first example and after `system_continue/3` in the second. All example started on first column of the line.  not at my desk right now but if you need more let me know what will check in 1 hour or so :)

**Comment by benoitc** [comment]
as an example, you have the following code:

```erlang
test() ->
  case ets:new(?TAB, [set, named_table, public,
```

Type enter after the comma, it will go at the column 4:

```erlang
test() ->
  case ets:new(?TAB, [set, named_table, public,
    {read_concurrency, true}
    
```

**Comment by benoitc** [comment]
(updated above to add the vim example)

**Comment by ignatov** [comment]
Thanks for the repro

**Comment by benoitc** [comment]
@ignatov any idea where I should look to fix that issue? It's actually stopping me to use intellij  :( So if I could help...

**Comment by ignatov** [comment]
Please try the latest build from the master branch – https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_IntellijErlang_Tests&guest=1

**Comment by benoitc** [comment]
@ignatov Thanks for the quick fix, it works for the case above, however it doesn't work for this one:

```erlang
  lists:foldl(fun(A, Acc) ->
```

type enter, you have in intellij:
```erlang
  lists:foldl(fun(A, Acc) ->
    [A| Acc]
```

where in vim you have:

```erlang
fun() ->
    lists:foldl(fun(A, Acc) ->
                    [A | Acc]
```

It also doesn't work for this one:

in intellij:

```erlang
-export([system_continue/1,])
```

Then type enter after `/1,`:

```erlang
-export([system_continue/3,
  system_terminate/4])
```

where in vim/emacs you have:

```erlang
-export([system_continue/3,
         system_terminate/4
```

Hope it helps. Let me know if you need some tests.

**Comment by ignatov** [comment]
Please create a separate issue for each case.

**Comment by benoitc** [comment]
@ignatov done.

**Comment by ignatov** [comment]
Thanks
