### ISSUE TITLE
error with   erlang*.el on android studio 2.2 and otp 19.0 

### ISSUE THREAD

**Issue by csbssp** [ignatov/intellij-erlang#749]
9:51:05 Plugin Error: Erlang threw an uncaught Error. Disable Plugin
9:51:05 Error
          Error while indexing /path-to-otp/otp_src_19.0/lib/tools/emacs/erlang-eunit.el
          To reindex this file IDEA has to be restarted: org.intellij.erlang.parser._ErlangLexer: Error: could not match input
9:51:07 Error: org.intellij.erlang.parser._ErlangLexer: Error: could not match input

**Comment by ignatov** [comment]
Please provide steps for reproduce.

**Comment by chenshaobo** [comment]
This error occures when I open an Erlang project on Android Studio 2.2 . 
I have used IDEA 2016.2 instead of  Android Studio 2.2 and  everything is fine. @ignatov

**Comment by ignatov** [comment]
That's strange.
