### ISSUE TITLE
formatting error for 'catch' keyword

### ISSUE THREAD

**Issue by brigadier** [ignatov/intellij-erlang#754]
Now:

```
test() ->
        catch 2 / 0,
    abc.
```

 Should be 

```
test() ->
    catch 2 / 0,
    abc.
```

**Comment by ignatov** [comment]
Fixed in https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_IntellijErlang_Tests/971825:id/Erlang-0.9.923.zip?guest=1
