### ISSUE TITLE
Not able to import rebar3 project into Intellij

### ISSUE THREAD

**Issue by Keam** [ignatov/intellij-erlang#755]
Hi,
I'm not able to import rebar3 project into Intellij. The version field shows up "N/A". I installed and compiled rebar3 in /usr/local/bin/rebar3. I have Mac OS 10.10.5 and I'm running: 

IntelliJ IDEA 2016.2
Build #IC-162.1121.32, built on July 9, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I'm using your plugin but I'm not able to import rebar3 projects. not sure why intellij is not seeing version number of rebar3. Any guidance would be appreciated.

**Comment by ignatov** [comment]
Duplicates #704
