### ISSUE TITLE
Link to intellij documentation is broken

### ISSUE THREAD

**Issue by marco-m** [ignatov/intellij-erlang#760]
The link in the project description is broken:
![intellij-link](https://cloud.githubusercontent.com/assets/3075069/17410268/2d0f1c9c-5a73-11e6-92d9-7121e52dfbd1.png)

I suggest replacing with something like https://www.jetbrains.com/help/idea/2016.2/getting-started-with-erlang.html

**Comment by ignatov** [comment]
Done, thanks
