### ISSUE TITLE
Erlang development on Windows with your plugin

### ISSUE THREAD

**Issue by joanlopez** [ignatov/intellij-erlang#763]
Hi,

Some months ago I've been developing some Erlang modules for Ejabberd. Those days I was developing with Vi/m in a Linux server.

Now I want to follow with my Erlang developments, but now, I want to develop on my main work computer. I've been researching and I've found your plugin to work with IntelliJ.

But now, I need the SDK (also EUnit for testing and so on). 

Is there anyway to get the SDK and all the needed dependencies to configure my development environment in Windows without having to use Cygwin and similars to download compilers, compile Erlang source code, etc....?

I hope yes, otherwise it'll be a mess..

Thanks a lot!

**Comment by NobbZ** [comment]
No messing wit cygwin. Just use the installer provided on the erlang
homepage or install erlang via chocolatey.

Joan Lopez <notifications@github.com> schrieb am Mi., 14. Sep. 2016 14:13:

**Comment by joanlopez** [comment]
Yo mean the ```OTP 19.0 Windows 64-bit Binary File (102501445)``` on http://www.erlang.org/downloads?

Thanks!

**Comment by NobbZ** [comment]
Choosing the right version does depend on the system you are developing on
and the system you are targetting. I do maintain a legacy OTP-App which has
to run on 16B3 on Windows and Linux, so I have that one installed, but the
one you are mentioning is the most current version.

PS: beware your CPUs architecture

Joan Lopez <notifications@github.com> schrieb am Mi., 14. Sep. 2016 um
16:30 Uhr:

**Comment by joanlopez** [comment]
Thanks for your help @NobbZ!
Finally I've the Erlang environment working!!
PS: https://www.jetbrains.com/help/idea/2016.2/getting-started-with-erlang.html
