### ISSUE TITLE
Support for arguments with spaces

### ISSUE THREAD

**Issue by durfeekth** [ignatov/intellij-erlang#764]
Are there any plans to implement support for run configurations in which the a function call takes a string with spaces as an argument? I can run a program through the erlang shell with this sort of argument, such as:
>hello:do_stuff("This is my argument!"). %Calls [do_stuff/1]

but the run configuration tool splits this up into four arguments instead. I've tried single and double quotes, as well as backslashes, but these haven't had any effect.

**Comment by ignatov** [comment]
Please enjoy with spaces!
![screenshot 2016-10-12 00 35 01](https://cloud.githubusercontent.com/assets/426890/19289509/cbe480fc-9013-11e6-972a-abb11b08bc7b.png)

**Comment by ignatov** [comment]
Please try https://teamcity.jetbrains.com/viewLog.html?buildId=881580&tab=artifacts&buildTypeId=IntellijIdeaPlugins_IntellijErlang_Tests
