### ISSUE TITLE
Problem with altering PATH variable

### ISSUE THREAD

**Issue by CO600-ol38** [ignatov/intellij-erlang#767]
I am a Windows-user and the PATH envVar for Erlang-shell, I believe, should be altered to include the path "C:\Program Files\erl8.1\bin\". I have done this using 'os:putenv("path", val).' .

But when I try to compile Rebar it STILL SAYS escript.exe un-recognized.

Please tell me where I went wrong?

**Comment by deadok22** [comment]
Hi @CO600-ol38,

[this page](https://www.jetbrains.com/help/idea/2016.1/getting-started-with-erlang.html) recommends you add that directory to PATH after you install Erlang.

Also, since you have this same problem when you run 'cmd.exe' not through the Erlang-shell, the problem seems to have nothing to do with the plugin. 

Let me know if this helps

**Comment by CO600-ol38** [comment]
I'm sorry but what's the difference between the PATH you said and the PATH I said?

**Comment by deadok22** [comment]
I'm not sure I understood your question. We both refer to PATH environment variable.

In your initial question you said that you called ```os:putenv(...)``` in an Erlang shell, then you compiled Rebar and were surprised escript.exe wasn't found. How exactly did you try to compile Rebar? Did you use the same process you issued ```os:putenv(...)``` in?

**Comment by deadok22** [comment]
@CO600-ol38 could you make a comment on what the problem was? It could be you're not the only one having this problem.

**Comment by CO600-ol38** [comment]
The problem was that it was unclear to me exactly what PATH variable it was refering to and what it should exactly be set to.
And even when it was finally understood what it should be. The BATCH-file 'bootloader' never seemed to work as a '.exe' it referenced could never be found.
I assume the reason you alter the PATH is so it can find this file; but it just isn't working for me.
Probably because it's Windows :/
