### ISSUE TITLE
Vanishing beam files

### ISSUE THREAD

**Issue by kanga-roo** [ignatov/intellij-erlang#771]
My project is developing until suddenly the beam files vanish;
![image](https://cloud.githubusercontent.com/assets/12368392/20236029/89b032a4-a8f9-11e6-8b1d-1250b6e34df0.png)

**Comment by ignatov** [comment]
Could you please attach a sample project.

**Comment by kanga-roo** [comment]
-module(wxcd01).
-include_lib("wx/include/wx.hrl").
-export([start/0, make_window/0, loop/1, cntdwn/2]).
%% API
start() ->
  State = make_window(),
  loop(State),
  wx:destroy().

make_window() ->
  Server = wx:new(),

  Frame = wxFrame:new(Server, -1, "Countdown",
    [{style, ?wxDEFAULT_FRAME_STYLE}, {size, {300, 200}}]),
  wxFrame:center(Frame),
  Panel = wxPanel:new(Frame),
  wxWindow:setBackgroundColour(Panel, ?wxLIGHT_GREY),

  T1001 = wxTextCtrl:new(Panel, 1001, [{value, "10"}]),
  ST2001 = wxStaticText:new(Panel, 2001, "OutputArea", []),
  B101 = wxButton:new(Panel, 101, [{label, "&Countdown"}]),
  B102 = wxButton:new(Panel, ?wxID_EXIT, [{label, "&Exit"}]),

  OuterSizer = wxBoxSizer:new(?wxHORIZONTAL),
  MainSizer = wxBoxSizer:new(?wxVERTICAL),
  InputSizer = wxStaticBoxSizer:new(?wxHORIZONTAL, Panel, [{label, "Enter an integer"}]),
  ButtonSizer = wxBoxSizer:new(?wxHORIZONTAL),

  

  wxSizer:add(InputSizer, T1001, []),
  wxSizer:add(InputSizer, 40, 0, []),

  wxSizer:addSpacer(MainSizer, 10),  %spacer
  wxSizer:add(MainSizer, InputSizer, []),
  wxSizer:addSpacer(MainSizer, 5),  %spacer

  wxSizer:add(MainSizer, ST2001, []),
  wxSizer:addSpacer(MainSizer, 10),  %spacer

  wxSizer:add(ButtonSizer, B101, [{proportion, 1}, {flag, ?wxSHAPED bor ?wxALIGN_LEFT bor ?wxALIGN_BOTTOM}]),
  wxSizer:add(ButtonSizer, B102, [{proportion, 2}, {flag, ?wxSHAPED bor ?wxALIGN_RIGHT bor ?wxALIGN_BOTTOM}]),
  wxSizer:add(MainSizer, ButtonSizer, [{proportion, 0}, {flag, ?wxALIGN_CENTER_HORIZONTAL}]),
  wxSizer:addSpacer(ButtonSizer, 10),

  wxSizer:addSpacer(OuterSizer, 20), % spacer
  wxSizer:fit(OuterSizer, Panel),
  wxSizer:add(OuterSizer, MainSizer, []),

%% Now 'set' OuterSizer into the Panel
  wxPanel:setSizer(Panel, OuterSizer),
%%  wxFrame:fit(Panel),
  wxFrame:show(Frame),

%% create 2 listeners
  wxFrame:connect(Frame, close_window),
  wxPanel:connect(Panel, command_button_clicked),

%% the return value, which is stored in State
  {Frame, T1001, ST2001, self()}.

loop(State) ->
  {Frame, T1001, ST2001, Pid} = State,  % break State back down into its components
  io:format("--waiting in the loop--~n", []), % optional, feedback to the shell
  receive

  % a connection get the close_window signal
  % and sends this message to the server
    #wx{event = #wxClose{}} ->
      if
        Pid /= self() -> Pid ! {-1};
        true -> ok
      end,
      io:format("~p Closing window ~n", [self()]), %optional, goes to shell
      %now we use the reference to Frame
      wxWindow:destroy(Frame),  %closes the window
      ok;  % we exit the loop

    #wx{id = ?wxID_EXIT, event = #wxCommand{type = command_button_clicked}} ->
      %%     {wx, ?wxID_EXIT, _,_,_} ->
      %this message is sent when the exit button (ID 102) is clicked
      %the other fields in the tuple are not important to us.
      if
        Pid /= self() -> Pid ! {-1};
        true -> ok
      end,
      io:format("~p Closing window ~n", [self()]), %optional, goes to shell
      wxWindow:destroy(Frame),
      ok;  % we exit the loop

    #wx{id = 101, event = #wxCommand{type = command_button_clicked}} ->
      %this message is sent when the Countdown button (ID 101) is clicked
      T1001_val = wxTextCtrl:getValue(T1001),
      case is_valid_list_to_integer(T1001_val) of
        true ->
          T1001_int = list_to_integer(T1001_val),
          MyPid = self(),
          CntdwnPid = spawn(fun() -> cntdwn(T1001_int, MyPid) end);
        _ ->
          wxStaticText:setLabel(ST2001, "Only integers are allowed"),
          CntdwnPid = Pid
      end,
      loop({Frame, T1001, ST2001, CntdwnPid});
    {0} ->
      OutputStr = "ZERO",
      wxStaticText:setLabel(ST2001, OutputStr),
      loop(State);

    {N} ->
      OutputStr = integer_to_list(N),
      wxStaticText:setLabel(ST2001, OutputStr),
      loop(State);

    Msg ->
      %everything else ends up here
      io:format("loop default triggered: Got ~n ~p ~n", [Msg]),
      loop(State)

  end.

cntdwn(N, Pid) when N > 0 ->
  % assumes N is an integer
  io:format("~w~n", [N]),
  Pid ! {N},
  receive
    {-1} -> io:format("Cancelled~n"),
      ok
  after 1000 ->
    cntdwn(N - 1, Pid)
  end;
cntdwn(_, Pid) ->
  io:format("ZERO~n"),
  Pid ! {0},
  ok.

is_valid_list_to_integer(Input) ->
  try list_to_integer(Input) of
    _An_integer -> true
  catch
    error: _Reason -> false  %Reason is badarg
  end.

I am not sure if the fault is with the above code or my setup. I have another file of identical code that is yet to lose its beam files. So, it still runs. Thank you for investigating.

**Comment by ignatov** [comment]
Please try the right configured project with your source file –
[erl-wx.zip](https://github.com/ignatov/intellij-erlang/files/588060/erl-wx.zip). It works fine for me.

**Comment by kanga-roo** [comment]
Thanks Sergey, I knew the code was not an issue. So, i imported your erl-wx.zip file [above], renamed it, built and rebuilt it with still no sign of beam files. Where do you think i should i look?

**Comment by kanga-roo** [comment]
When I searched Win 10 for the beam file it was found. When opened in IJ the warning read;
'File was loaded in the wrong encoding: UTF-8'
with the option to;
'reload in another encoding'
If i should reload, which encoding should be selected from the drop-down options?

**Comment by kanga-roo** [comment]
With the latest plug-in this issue seems to be resolved. Thank you, Sergey!

**Comment by ignatov** [comment]
That's great!
