### ISSUE TITLE
Don't want rebar command run under escript

### ISSUE THREAD

**Issue by helloyan** [ignatov/intellij-erlang#772]
I test that rebar command path settings is use escript to run ,but  the rebar or rebar.cmd can run directly,how can i set to use rebar command  directly?

**Comment by NobbZ** [comment]
`rebar` it self is an erlang script, so you need `escript` to run it. `rebar.cmd` is just a wrapper that actually does nothing else than `escript c:\full\path\to\rebar`.

Perhaps you can explain in more detail what you try to achieve?

**Comment by helloyan** [comment]
in rebar3 , i can run it directly, not use escript, and aslo it can run under escript

What i want is to keep it clean, because i don't want to set path in system environment

**Comment by NobbZ** [comment]
What exactly do you mean bi running it directly? The file `rebar`(`3`) can't be run directly in windows. Whenever you type only that name in your terminal windows dies automatically put different ending a behind it that it knows how to execute and looks for appropriate files in the current working dir and then the path until it finds the file. Then it is executed. 

And usually this is the program rebar.cmd or rebar.bat for windows systems which is basically as I showed you above. 

Even under Linux where better magic is happening, both needs to be in path, escript as well as rebar.

**Comment by helloyan** [comment]
![image](https://cloud.githubusercontent.com/assets/1699033/20859090/abfe637a-b98f-11e6-94d6-8e1598b534b7.png)


I use the offical rebar and compile it under windows, and modify the rebar.cmd. And yes , i know the rebar.cmd is a command that run escript.exe rebar3 


![image](https://cloud.githubusercontent.com/assets/1699033/20859097/c0a1be30-b98f-11e6-8871-decc1260fae3.png)
![image](https://cloud.githubusercontent.com/assets/1699033/20859102/dfc026d0-b98f-11e6-892b-766d64ae00ba.png)
