### ISSUE TITLE
erlang 19 -  gen_statem template

### ISSUE THREAD

**Issue by Revent** [ignatov/intellij-erlang#774]
be or not to be?

**Comment by ignatov** [comment]
Please provide a desired template and I could easily bundle it.

**Comment by neeraj9** [comment]
I believe you can use this[1] as integrated into vim erlang templates.

[1] https://github.com/vim-erlang/vim-erlang-skeletons/blob/master/plugin/templates/gen_statem

**Comment by neeraj9** [comment]
By the way- the intellij-erlang rocks. Although, I am a vim guy but the it is awesome for getting new team members getting on board with Erlang/OTP. Thanks!

**Comment by ignatov** [comment]
Fixed in https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_IntellijErlang_Tests/971825:id/Erlang-0.9.923.zip?guest=1
