### ISSUE TITLE
unresolved ?FUNCTION_NAME and ?FUNCTION_ARITY macroses

### ISSUE THREAD

**Issue by brigadier** [ignatov/intellij-erlang#777]
?FUNCTION_NAME and ?FUNCTION_ARITY - these two macroses were added in Erlang 19 release. Currently plugin does not know about them and marks them as unresolved.

**Comment by ignatov** [comment]
Please use Erlang.zip from https://teamcity.jetbrains.com/viewLog.html?buildId=965316&tab=artifacts&buildTypeId=IntellijIdeaPlugins_IntellijErlang_Tests
