### ISSUE TITLE
pre-release not downloadable

### ISSUE THREAD

**Issue by NobbZ** [ignatov/intellij-erlang#779]
README.md:
> ## Pre-release builds
> [Download](https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_IntellijErlang_Tests/.lastSuccessful/Erlang-0.9.923.zip?guest=1)  the latest successful plugin, [...]

That link gives me a 404. I'd really like to test the pre-release though.

**Comment by ignatov** [comment]
Thanks, fixed, please try the latest one.

**Comment by NobbZ** [comment]
Works now, thank you!
