### ISSUE TITLE
Bifs not resolving

### ISSUE THREAD

**Issue by walrusVision** [ignatov/intellij-erlang#782]
Same issues as the closed ticket #365. Bifs are not resolving unless prefixed with ```erlang:```

Using Intellij 2016.3.4, OTP-19.2, and version 0.9.932 of the plugin.

**Comment by ignatov** [comment]
That's strange, but I'll have a look.

**Comment by walrusVision** [comment]
I finally found the problem. I had been setting up erlang under `Platform Settings` -> `SDKs` in the Project Structure window, but to get it detect the Bifs you also have to add the erlang lib path to the Global Libraries. Once that's added the Bifs resolve correctly

**Comment by ignatov** [comment]
Cool
