### ISSUE TITLE
Plugin does not work with IntelliJ IDEA 2017.1 EAP

### ISSUE THREAD

**Issue by marcphilipp** [ignatov/intellij-erlang#784]
First of all, thank you for a great plugin!

When using IntelliJ IDEA 2017.1 EAP I get the following error message when opening a project that used to work on 2016.3.2:

> **Unknown Module Type**
> Cannot determine module type ("ERLANG_MODULE") for the following module:"extensions"
> The module will be treated as a Unknown module.

Syntax highlighting works partially (atoms and variables look the same) but there's not support for jumping to a function definition etc.

**Comment by ignatov** [comment]
OK, I'll rebuilt the plugin for 2017.1.

**Comment by ignatov** [comment]
I've uploaded the new version 0.9.935 – https://plugins.jetbrains.com/idea/plugin/7083-erlang

**Comment by ignatov** [comment]
My pleasure ;)
