### ISSUE TITLE
Zotonic on intellij-erlang

### ISSUE THREAD

**Issue by alvaropag** [ignatov/intellij-erlang#788]
I didn't found a forum/mailing list for help, so I'm asking in this issue, if there is a better place to asks this questions, please let me know.

-------------------------------------------------------------------------------------------------------------------------------------------

Hello,

I'm trying to use intellij-erlang to develop [Zotonic](http://zotonic.com/) websites but I'm having some troubles and would like some help. 

The first test I did was with phpStorm (2017.1) and the latest intellij-erlang (0.9.935), but with this IDE version I can't create an Erlang Project, the option is not shown on File -> New -> Project.... 
So I downloaded intellij IDEA 2017.1.1 and installed the same intelllij-erlang plugin. Now I can create projects and all, but some things are still not working right.

My initial zotonic structure was ~/devel/zotonic (the source of zotonic project - using rebar2) and ~/devel/zotonic_data (my modules and sites - no rebar, they are injected inside the vm via zotonic using a configuration file). If I configure the the intellij project using modules in different folders, then compilations errors show up, like includes not found. 

To solve this I had to put everything inside the ~/devel/zotonic folder (but I would prefer the other way around). In both cases all the src folders were marked as Source and include folders marked as Includes. Even on the same source tree, includes from one module can't be resolved inside another module, but on the erlang runtime they are found and everythings works ok.

Another problem is how to debug zotonic inside intellij. Zotonic have a shell script located at "bin/zotonic debug" command that starts everything. I tried to connect using erlang-remote, but it didn't work... using an erlang console also resulted in errors.

The remaining problem is the .tpl files. Zotonic uses Django Template Language as it's html template language, but I could not get intellij to recognize the django tags. I installed the Python plugin and Djaneiro plugin with no success (by the way, PyCharm 2017.1 also doesn't have the Erlang Project option at File -> New -> Project...). Does anyone uses dtl on intellij? Should I enable the python facet on the project? 

I'm still using the 30-day trial and I'm loving the IDE and the erlang plugin, the auto-complete is awesome and the double shift (search everywhere) is a killer feature. If anyone have some tips to better configure zotonic inside intellij-erlang please let me know.

Cheers.

**Comment by ignatov** [comment]
Hi, the plugin doesn't push you to use hard-coded project structure models, feel free to choose whatever you want.
For PhpStorm, PyCharm and other small IDEs you can create just the simplest PHP or Python project, just a folder, and put your Erlang files there.

I'll investigate how to add Erlang in File -> New -> Project.... in PhpStorm.

Thanks.

**Comment by Dirklectisch** [comment]
About configuring those Django templates. I got it work by doing the following somewhat counter intuitive steps.

1. Installing the official Python plugin
2. Add the `*.tpl` pattern to HTML under the file type preferences
3. Configure Django as the template language under the Python Template Languages preference

**Comment by alvaropag** [comment]
That's how I got it working. 

But I guess zotonic tpl is a bit different from python, because it still shows me some errors when I pass variables like `{% include  "path\to\template" id=id %}` on id=id it marks an error, but it's usable.
