### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by byaruhaf** [ignatov/intellij-erlang#789]
Autocomplete is not working on any standard library module's 

IntelliJ IDEA 2017.1.1
Build #IC-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4
erlang/OTP: stable 19.3

**Comment by ignatov** [comment]
Could you please provide an example and verify that you have the Erlang SDK, which is setup properly.

**Comment by byaruhaf** [comment]
hi

when I try to get functions for the **io** module this is what I see:

![image](https://cloud.githubusercontent.com/assets/4116539/25493362/8febb74e-2b7e-11e7-8fc9-7968ba6d5a47.png)


when I try to get functions for the **lists** module this is what I see:
![image](https://cloud.githubusercontent.com/assets/4116539/25493424/d04a23de-2b7e-11e7-9ee8-31940d42d5db.png)

so the Erlang SDK should be setup properly  cause the lists module works but io module fails

**Comment by byaruhaf** [comment]
it seems I had an issue with the Erlang SDK; all is now fine
