### ISSUE TITLE
current plugin is incompatible with Idea 2017.2 EAP

### ISSUE THREAD

**Issue by marco-m** [ignatov/intellij-erlang#792]
When opening any Erlang project I get
```
Unknown Module Type
Cannot determine module type ("ERLANG_MODULE") for the following module:"spoj"
The module will be treated as a Unknown module.
```

**Comment by ignatov** [comment]
Hi @marco-m! What product and plugin do you use?

**Comment by marco-m** [comment]
Hello Sergey,

IntelliJ IDEA (Community Edition) 2017.2 EAP
Build #IC-172.1909.2, built on May 2, 2017
JRE: 1.8.0_152-release-837-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

and the Erlang plugin version 0.9.939 (the latest).

**Comment by ignatov** [comment]
The latest plugin isn't compatible with 2017.2 EAP. I'll try to publish something for 2017.2 soon.

**Comment by marco-m** [comment]
thanks!

**Comment by bsnote** [comment]
Hi @ignatov, any update on this issue?
Thanks!

**Comment by ignatov** [comment]
Fixed, please install the latest build from the IDE.
https://plugins.jetbrains.com/plugin/7083-erlang/update/35286

**Comment by marco-m** [comment]
Thanks!

**Comment by bsnote** [comment]
It's still incompatible with the latest version:
IntelliJ IDEA (Community Edition) 2017.2 EAP
Build #IC-172.2273.8, built on May 18, 2017

From plugin's page:
Version: 0.9.947
Compatible builds: 172.1909—172.1909.*

Can it be set to at least 172.1909—172.* ?

**Comment by ignatov** [comment]
Uploaded – https://plugins.jetbrains.com/plugin/7083-erlang/update/35446

Feel free to open a new PR against the *172* branch next time; it's quite easy, you can use just Github for such kind of pull requests – https://github.com/ignatov/intellij-erlang/commit/8405274334f87b9c788adc316409a9a7c6aa37ae
