### ISSUE TITLE
Plugin is not compatible with the latest IntelliJ IDEA 2017.2

### ISSUE THREAD

**Issue by dsrosario** [ignatov/intellij-erlang#800]
After updating the IntelliJ to the latest version, the plugin failed to load. If I uninstall it, it won't show up at the plugin search page. Tried to install the plugin manually (downloaded Erlang-0.9.950.zip) and it also failed to install.

**Comment by doobinay** [comment]
`vi ~/.IdeaIC2017.2/config/plugins/Erlang/META-INF/plugin.xml`
until-build="172.*"

**Comment by ignatov** [comment]
Uploaded the new version.
