### ISSUE TITLE
PyCharm 2017.1.5 doesn't recognize ERLANG_MODULE

### ISSUE THREAD

**Issue by alvaropag** [ignatov/intellij-erlang#801]
Hello,

I'm using the Erlang plugin on PyCharm but it gives me an error. Is PyCharm compatible with the Erlang plugin? I'm using version 0.9.939.

This is the error message:
18/07/17
14:27	Unknown Module Type
			Cannot determine module type for the following modules:
			
			"afunix" (type 'ERLANG_MODULE')
			"amqp_client" (type 'ERLANG_MODULE')
			"bcrypt" (type 'ERLANG_MODULE')
			"bear" (type 'ERLANG_MODULE')
			"bert" (type 'ERLANG_MODULE')
			"cf" (type 'ERLANG_MODULE')
			"depcache" (type 'ERLANG_MODULE')
			"dh_date" (type 'ERLANG_MODULE')
			"diffy" (type 'ERLANG_MODULE')
			"dispatch_compiler" (type 'ERLANG_MODULE')
			"edown" (type 'ERLANG_MODULE')
			"eiconv" (type 'ERLANG_MODULE')
			"emqtt" (type 'ERLANG_MODULE')
			"emqtt_plugin_admin" (type 'ERLANG_MODULE')
			"epgsql" (type 'ERLANG_MODULE')
			"erlang_localtime" (type 'ERLANG_MODULE')
			"erlpass" (type 'ERLANG_MODULE')
			"erlware_commons" (type 'ERLANG_MODULE')
			"exif" (type 'ERLANG_MODULE')
			"exometer" (type 'ERLANG_MODULE')
			"exometer_collectd" (type 'ERLANG_MODULE')
			"exometer_core" (type 'ERLANG_MODULE')
			"filezcache" (type 'ERLANG_MODULE')
			"folsom" (type 'ERLANG_MODULE')
			"gen_smtp" (type 'ERLANG_MODULE')
			"... (show balloon)

14:30	Error Loading Project: Cannot load 51 facets Details...

---------
Thanks!

**Comment by ignatov** [comment]
Seems, that you've tried to open an IntelliJ project with PyCharm.
PyCharm is compatible with Erlang plugin, but it doesn't have any modules and facets. Please open your project in IntelliJ.

**Comment by alvaropag** [comment]
Yep, I had to create the project with IntelliJ because the PyCharm IDE doesn't have an Erlang option in the New Project menu. So, I created a Django project and imported my Erlang files and it worked. Thanks!
