### ISSUE TITLE
Plugin does not work with IntelliJ IDEA 2017.3 EAP

### ISSUE THREAD

**Issue by ikhvostenkov** [ignatov/intellij-erlang#810]
IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.2099.14, built on September 6, 2017
IntelliJ IDEA EAP User
Expiration date: October 6, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

![screen shot 2017-09-13 at 15 23 03](https://user-images.githubusercontent.com/861305/30379781-eb2f2402-9897-11e7-898c-a7a6a7dc25f2.png)
![screen shot 2017-09-13 at 15 23 46](https://user-images.githubusercontent.com/861305/30379782-eb392484-9897-11e7-9d39-d0c10263dc2d.png)

**Comment by ignatov** [comment]
I've just uploaded the fresh version of the plugin for 2017.3 builds, enjoy!

**Comment by ikhvostenkov** [comment]
Awesome, this works, thank you.
