### ISSUE TITLE
GoLand Support

### ISSUE THREAD

**Issue by sheb-gregor** [ignatov/intellij-erlang#815]
Hi! Will the plugin be compatible with GoLand?

I updated Gogland EAP to GoLand 2017.3 and can not install the Erlang plugin. Get the error message:
`"Plugin 'Erlang' is incompatible with this installation"`
![screen shot 2017-11-14 at 12 45 27 pm](https://user-images.githubusercontent.com/11243996/32776308-ce59513a-c93a-11e7-8a23-dfe98d159687.png)

About GoLand:
![screen shot 2017-11-14 at 12 47 26 pm](https://user-images.githubusercontent.com/11243996/32776343-e6220de8-c93a-11e7-83da-7a798b02ea65.png)

**Comment by ignatov** [comment]
Thanks for the reminder, I'll update the Erlang plugin for the 173 platform.

**Comment by ignatov** [comment]
I've just uploaded the fresh version of the plugin for 2017.3 builds, enjoy!

**Comment by sheb-gregor** [comment]
Awesome! Thanks!
