### ISSUE TITLE
Setup SDK

### ISSUE THREAD

**Issue by saleyn** [ignatov/intellij-erlang#817]
When loading the plugin to other versions of the IDE (e.g. JetBrains CLion), it works fine except there seems to be no way to setup/configure "Erlang SDK", since there's no separate project settings option.

Is there any way to configure the "Erlang SDK" to recognize the erl install path in CLion?  In the image below, clicking on the "Setup SDK" does nothing:

![image](https://user-images.githubusercontent.com/272543/34622859-df39ef0e-f21c-11e7-819c-f4f7aa39c6d1.png)

**Comment by ignatov** [comment]
@saleyn Please try the next build with the fix at https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_IntellijErlang_Tests&guest=1; I suppose the number should be 967.

**Comment by saleyn** [comment]
It works! You are the man! :)
