### ISSUE TITLE
rebar3 compilation interprets warnings as errors 

### ISSUE THREAD

**Issue by bryanhuntesl** [ignatov/intellij-erlang#818]
Compiling the project [tanodb](https://github.com/marianoguerra/tanodb)  under Erlang 20 - a lot of compiler warnings are generated regarding deprecation warnings - however the top level rebar.config does not set 'warnings_as_errors' as a compiler option and it compiles fine at the command line ([build-log.txt](https://github.com/ignatov/intellij-erlang/files/1636108/build-log.txt))

It would be nice if Intellij didn't interpret warnings as errors as it would allow me to build this project from within Intellij.

**Comment by ignatov** [comment]
Could you please provide a small example for reproducing. That will speed up the fix :)

**Comment by bryanhuntesl** [comment]
Hi @ignatov - sorry for the delay - I've created a branch [example-with-intellij-config](https://github.com/bryanhuntesl/tanodb/tree/example-with-intellij-config) containing all the Intellij files on a test [tannodb](https://github.com/marianoguerra/tanodb) project. 

That stuff compiles with rebar3 on the command line but fails from within Intellij :

<img width="1114" alt="screen shot 2018-02-01 at 16 29 49" src="https://user-images.githubusercontent.com/31992054/35690361-91e00354-076d-11e8-8931-2760c63d1481.png">

**Comment by ignatov** [comment]
@bryanhuntesl Merci!

**Comment by bryanhuntesl** [comment]
пожалуйста
