### ISSUE TITLE
gen_statem, missing callback_mode 

### ISSUE THREAD

**Issue by Gsantomaggio** [ignatov/intellij-erlang#822]
`gen_statem` should implement the `callback_mode()`.

When you create the `gen_statem` template  you get this error:
```
Eshell V9.2  (abort with ^G)
1> c(test).
test.erl:12: Warning: undefined callback function callback_mode/0 (behaviour 'gen_statem')
{ok,test}
```

It is enough to add the callback in this way:
```
callback_mode() ->
    handle_event_function.
```

[Erlang%20Gen%20Statem.erl.ft](https://github.com/ignatov/intellij-erlang/blob/master/resources/fileTemplates/internal/Erlang%20Gen%20Statem.erl.ft)  should be the right place, right?

I can add it. 

Thanks

**Comment by ignatov** [comment]
Right, could you please create a PR?

**Comment by Gsantomaggio** [comment]
sure!
