### ISSUE TITLE
How to support 2018.1 or later in IntelliJ

### ISSUE THREAD

**Issue by CasterKKK** [ignatov/intellij-erlang#824]
Hi,
I found that the plugin is only support 2017.3, how could I use this under 2018.1?
You know as a Java and Erlang programmer, there are lots of new features in 2018.1, I cannot abandon them...

**Comment by byyo** [comment]
+1 would love to see support for this plugin in the new version of IntelliJ!

**Comment by ignatov** [comment]
Uploaded the 0.11.971, thanks for the patience.

**Comment by byyo** [comment]
thanks!
