### ISSUE TITLE
Plugin does not work with Pycharm 2018.1

### ISSUE THREAD

**Issue by zp-sd** [ignatov/intellij-erlang#828]
It looks like plugin is not working anymore after an update?

<img width="478" alt="screen shot 2018-03-31 at 09 06 37" src="https://user-images.githubusercontent.com/28924437/38160754-ec6f8588-34c2-11e8-8d00-749895e20c4b.png">
<img width="360" alt="screen shot 2018-03-31 at 09 06 51" src="https://user-images.githubusercontent.com/28924437/38160755-ed9c2a10-34c2-11e8-918e-295be09ae93d.png">

**Comment by zp-sd** [comment]
Yes, it worked some time ago after an update. I forgot to alter this ticket. Closing now.

**Comment by ignatov** [comment]
Thanks!
