### ISSUE TITLE
Perpetual Setup SDK prompt in WebStorm

### ISSUE THREAD

**Issue by cogitaria-admin** [ignatov/intellij-erlang#832]
All erl files in WebStorm (2017) have a header prompting to Setup SDK, even after setting up the SDK and applying.  No amount of application restarts, plug-in reinstalls or SDK setup attempts will fix this.

**Comment by ignatov** [comment]
Please attach your logs '''Help > Show logs in...''' and screenshot with Erlang SDK settings.

Works for with 2018.1
![image](https://user-images.githubusercontent.com/426890/38816576-663a226c-4164-11e8-8c02-839a92adec92.png)

**Comment by mockuniverse** [comment]
Upgraded to 2018 but I think the issue was the Path to the SDK was not pointing to the root 20.1.1 in my case.
