### ISSUE TITLE
IntelliJ 2018.2 support

### ISSUE THREAD

**Issue by byyo** [ignatov/intellij-erlang#837]
Just want to ask for a plugin update to support the new 2018.2 version. Thanks!

**Comment by kentkwan** [comment]
The same question I met. Touchbar supported is very important! Thx.

**Comment by ignatov** [comment]
I've just uploaded a fresh build, 0.11.985, sorry for the inconvenience.

**Comment by byyo** [comment]
Thank you @ignatov !
