### ISSUE TITLE
下载的项目用webstorm npm run dev打不开 并且报错,初级者求答，十分感谢

### ISSUE THREAD

**Issue by bingqingyujie** [ignatov/intellij-erlang#841]
2018/8/16
14:21	IDE and Plugin Updates: WebStorm is ready to update.

14:23	Unknown Module Type
		Cannot determine module type ("JAVA_MODULE") for the following module:"IHome"
		The module will be treated as a Unknown module.

14:23	Error Loading Project: Cannot load facet Web (IHome) Details...

14:23	Plugins Suggestion
		Features covered by IntelliJ IDEA Ultimate Edition (Java EE: EJB, JPA, Servlets) are detected.
		Check IntelliJ IDEA Ultimate Edition
		Do not suggest Ultimate Edition

**Comment by ignatov** [comment]
Looks like that the issue isn't about the Erlang plugin. Could you please describe what's happened and what's the problem?
