### ISSUE TITLE
Erlang/OTP 21 map guards support

### ISSUE THREAD

**Issue by 23ua** [ignatov/intellij-erlang#845]
In Erlang/OTP 21 two new map guards were added:
```
  OTP-15037    Application(s): compiler, erts
               Related Id(s): PR-1784, PR-1802

               Two new guards BIFs operating on maps have been added:
               map_get/2 and is_map_key/2. They do the same as
               maps:get/2 and maps:is_key/2, respectively, except that
               they are allowed to be used in guards.
```
Source: http://erlang.org/download/otp_src_21.0.readme

Usage of these guards In the latest version of the plugin (w/ Erlang 21 selected as a Project SDK) is being highlighted as an "Illegal guard expression" error:
<img width="353" alt="screen shot 2018-11-20 at 6 00 19 pm" src="https://user-images.githubusercontent.com/2116934/48785846-3c217f80-ecee-11e8-9787-bc725127f688.png">

**Comment by ignatov** [comment]
Thanks for reporting.
