### ISSUE TITLE
v0.11.1000 and IntelliJ 2018.3 Community Edition not allowing function name typing

### ISSUE THREAD

**Issue by alexchowle** [ignatov/intellij-erlang#849]
When trying to type a new function name, each character is deleted in the IDE. Parentheses are OK, though.

This is happening on Ubuntu 18.10 and Centos 7.

**Comment by ignatov** [comment]
Hi, could you please attach a video or a GIF? Also, logs are welcome.

**Comment by alexchowle** [comment]
[repro.zip](https://github.com/ignatov/intellij-erlang/files/2630307/repro.zip)

MP4 attached.

Also logs
[idea.log](https://github.com/ignatov/intellij-erlang/files/2630312/idea.log)

**Comment by alexchowle** [comment]
This is NOT an issue with the erlang plugin - the same problem occurs with markdown files, too.

**Comment by ignatov** [comment]
Hi, have you found an original issue?
