### ISSUE TITLE
Variable unbound incorrectly reported

### ISSUE THREAD

**Issue by paraparaman** [ignatov/intellij-erlang#855]
![image](https://user-images.githubusercontent.com/29219562/50771136-af924700-12c4-11e9-9c51-fc17ba89c583.png)

idea report B is unbound!

**Comment by loxs** [comment]
Also in cases like this. the `Friend` variable is both reported as not used and unbound:

<img width="792" alt="screenshot 2019-02-07 at 11 14 45" src="https://user-images.githubusercontent.com/162763/52401159-b5e53000-2ac9-11e9-9df3-d007de6e292a.png">

**Comment by ignatov** [comment]
Hi, thanks for reporting, could you please provide a piece of code not a screen shot?

**Comment by loxs** [comment]
Simplest snippet would be something like this:
```erlang
test_fun() ->
    case length(Lst = [1, 2, 3]) of
        3 -> Lst;
        _ -> not_3
    end.
```

**Comment by justintung** [comment]
when variable was defined at case sub statement,will get the "unbound"message

**Comment by kvakvs** [comment]
This is a duplicate of #819
Thank you for reporting
