### ISSUE TITLE
IntelliJ 2019.1 support

### ISSUE THREAD

**Issue by f3c0** [ignatov/intellij-erlang#857]
2019.1 RC is out, and probably the final will be soon.
Can you add 2019.1 support please?
thanks

**Comment by JakaBac** [comment]
[Latest Pre-Release build](https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_IntellijErlang_Tests/.lastSuccessful/intellij-erlang-0.11.%7Bbuild.number%7D.zip?guest=1) already works with 2019.1
