### ISSUE TITLE
includes root not exist

### ISSUE THREAD

**Issue by zihuangning** [ignatov/intellij-erlang#858]
idea:2019.1.1, erlang plugin: 0.11.1004
I have a project write in linux, and i move it to windows.
Whether I  open the project structure nor right click the fold , I cant find includes root...

**Comment by ignatov** [comment]
Could you please provide an example – a project sample or something.

**Comment by kvakvs** [comment]
Seems to be duplicate of #842
1. "mark as Includes Root" is not available
2. yellow bar "mark automatically include roots" is not doing anything because №1
