### ISSUE TITLE
Spell check for atom

### ISSUE THREAD

**Issue by zengjinc** [ignatov/intellij-erlang#860]
![spell](https://user-images.githubusercontent.com/25508891/59317317-e695da00-8cf4-11e9-9f12-42b7a4633e10.png)

like that.
Variable Iteeem have spell err, and Idea warning.
Atom falseeeee have spell err, but not warning.
This often causes case clause.
is there any solutions?

**Comment by ignatov** [comment]
Are you sure, that you'd like to see all misspelled atoms in your project under-waved?

**Comment by zengjinc** [comment]
> Are you sure, that you'd like to see all misspelled atoms in your project under-waved?

I am ok with that. Is there anything wrong with it ?
