### ISSUE TITLE
How to change the author, company, etc.. in the docstring for new files

### ISSUE THREAD

**Issue by aaronlelevier** [ignatov/intellij-erlang#861]
Is there a way to configure the values for the author, company, etc... that get set when creating a new Erlang file?  `author` is my unix username, but I'd like to change it to my full name. I'd like to change company maybe. It defaults to `<COMPANY>` so it seems like there's an environment variable that can be set or some way to configure this.

For versions of software, I'm using:

- Mac OSX High Sierra
- Erlang/OTP 20
- Erlang Intellij Plugin version v0.11.1003

Also, thank you for this great plugin for Intellij. I'm new to Erlang (in the last 2 months, coming from Python), and having this plugin has helped me so much get started. 

Thank you.

**Comment by skorobkov** [comment]
File | Setting | Editor | File and Code Templates
Tab "Includes"
Erlang Custom Template Variables
Change/add variables as you wish. 
<img width="1156" alt="Снимок экрана 2019-07-25 в 21 03 21" src="https://user-images.githubusercontent.com/8956153/61897460-be1e1400-af1f-11e9-9715-74ef648359f2.png">

**Comment by kvakvs** [comment]
@aaronlelevier did the reply above answer your question?

**Comment by aaronlelevier** [comment]
@kvakvs it did. Thank you so much. I had missed your first message. This is exactly what I was looking for. Thank you!
