### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by msilvestre** [ignatov/intellij-erlang#875]
On intellij latest version:

IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: terminal.buffer.max.lines.count=99999999, ide.tooltip.initialDelay=739
Non-Bundled Plugins: Twelf Plugin, codes.rudolph.idea.cfg, com.kaylerrenslow.plugin.armaplugin.id, io.protostuff.protostuff-jetbrains-plugin

**Comment by ignatov** [comment]
Hi, what does it mean – `Plugin not working`?

**Comment by msilvestre** [comment]
Never mind! I did not update the plugin.
