### ISSUE TITLE
IDE does not highlight same variable in all places in a function

### ISSUE THREAD

**Issue by vassilevsky** [ignatov/intellij-erlang#888]
Hi :)

I did a minimal repro:

```erlang
foo(Width, Bits, Value) ->
    <<_:16/bits, _:Width/bits, _/bits>> = Bits,
    <<Value:Width>>.
```

It highlights `Width` as the same variable:
* Either in lines 1 and 2
* Or in lines 2 and 3
* but not throughout the entire function

Not sure if this is a bug or I'm missing something :)

IntelliJ IDEA 2019.2.2 (Community Edition)
Build #IC-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: 
Non-Bundled Plugins: com.daylerees.rainglow, com.atlassian.bitbucket.references, ideanginx9, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, org.jetbrains.erlang, org.elixir_lang, izhangzhihao.rainbow.brackets, Docker, some.awesome

Erlang plugin version 0.11.1008

**Comment by kvakvs** [comment]
After a short investigation, it seems that the actual error here is that variable standing in the right part of binary expression element `<<_:Width/bits>>` should not be declaring a variable, while it does.
