### ISSUE TITLE
2020.1  is coming 

### ISSUE THREAD

**Issue by Revent** [ignatov/intellij-erlang#907]
when to be ready to new version

**Comment by aselder** [comment]
IntelliJ won't load Erlang/Elixir projects under 2020.1.
![Screen Shot 2020-04-09 at 11 18 38 AM](https://user-images.githubusercontent.com/11577/78927507-e1f49c00-7a53-11ea-84b6-158c8df2c71d.png)

**Comment by ignatov** [comment]
Hi! Here's an update https://plugins.jetbrains.com/plugin/7083-erlang/update/83262
Sorry for the delay.
