### ISSUE TITLE
can't suppress Unresolved function warning in macros

### ISSUE THREAD

**Issue by brigadier** [ignatov/intellij-erlang#941]
Impossible to suppress unresoved function warning in something like this
```erlang
-define(MACROS(Val), (persistent_term:get(Val)):myfun()).
```

this doesn't show any warnings:
```erlang
-define(MACROS(Val), Val:myfun()).
```

**Comment by ignatov** [comment]
I hope that will help you. 
![image](https://user-images.githubusercontent.com/426890/112724623-5191be80-8f25-11eb-9e5d-afb7ab862a2d.png)
