### ISSUE TITLE
Support for IntelliJ IDEA 2021.2

### ISSUE THREAD

**Issue by aml014-1** [ignatov/intellij-erlang#947]
Please upgrade to support IntelliJ IDEA 2021.2 (Community Edition)
IC-212.4746.92

**Comment by CrystalJewell** [comment]
WebStorm 2021.2 Build #WS-212.4746.80 would be great too <3

**Comment by michaelklishin** [comment]
Looks like https://github.com/ignatov/intellij-erlang/commit/849b62cdbb2992187b3731aef9c8a2c7e39da432 addressed this. 🙏 Now we have have to wait for a new release 😅

**Comment by ignatov** [comment]
I published https://plugins.jetbrains.com/plugin/7083-erlang/versions/stable/129974 last week. Enjoy!
