### ISSUE TITLE
OTP 25

### ISSUE THREAD

**Issue by artman41** [ignatov/intellij-erlang#970]
OTP 25.0-rc1 was [recently released](https://www.erlang.org/news/153)

Are there any plans to update the plugin to support the new keywords (`maybe...else...end`) and symbols (`?=`) prior to the official release?

**Comment by ignatov** [comment]
Hi, @artman41, I'm going to update the plugin. Thanks for pointing me to that update.

**Comment by artman41** [comment]
Hi @ignatov, any update on this?

**Comment by bighunter513** [comment]
@ignatov when will it support otp 25 grammra like maybe expr ?

**Comment by zyuyou** [comment]
[intellij-erlang-0.11.1150.zip](https://github.com/ignatov/intellij-erlang/files/9335203/intellij-erlang-0.11.1150.zip)
@artman41 have a try?

**Comment by artman41** [comment]
> [intellij-erlang-0.11.1150.zip](https://github.com/ignatov/intellij-erlang/files/9335203/intellij-erlang-0.11.1150.zip) @artman41 have a try?

Only just managed to get a chance to test this @zyuyou but it seems to work great 👍 

Will comment back on the thread if I see any issues

**Comment by zyuyou** [comment]
[intellij-erlang-0.11.1150.zip](https://github.com/ignatov/intellij-erlang/files/9390758/intellij-erlang-0.11.1150.zip)
recompiled for idea-2022.2.1

**Comment by zyuyou** [comment]
[intellij-erlang-0.11.1150.zip](https://github.com/ignatov/intellij-erlang/files/9390836/intellij-erlang-0.11.1150.zip)
recompiled for idea-2022.2.1

**Comment by zhuiyi9009** [comment]
how to resolve this
`maybe'expression require Erlang/OTP 25.0 with '-enable-feature maybe_expr` ? 
@zyuyou

**Comment by kvakvs** [comment]
Fixed by @zyuyou merged in `master` but not released yet
