### ISSUE TITLE
"Setup SDK" button suggests to configure the JDK isntead of the Erlang SDK

### ISSUE THREAD

**Issue by ljchen1** [ignatov/intellij-erlang#977]
IDEA 2022.1
Steps:
1. Create a project without Erlang SDK.
2. Open a Erlang file and click the `Setup SDK` in banner.

![image](https://user-images.githubusercontent.com/103916765/165742912-5ec2fc55-03b7-4f6a-99f2-11678df69b3b.png)

**Comment by kvakvs** [comment]
I believe this was fixed in recent weeks in `master`, possibly not released yet
