### ISSUE TITLE
Latest build artifact doesn't install in current version of Intellij IDEA.

### ISSUE THREAD

**Issue by ShawnMcCool** [ignatov/intellij-erlang#995]
![image](https://user-images.githubusercontent.com/560749/210179843-695e5d9e-7dea-42cc-9940-fde7d9d83abf.png)

I checked and there doesn't seem to be a version 223. Please advise.

**Comment by kvakvs** [comment]
There wasn't a release for 223 it seems and i cannot control the release cycle only maintain and merge the code. You can try this one i've built today from OTP 25 merge request and replace it later after the new release.
[intellij-erlang-0.11.SNAPSHOT.zip](https://github.com/ignatov/intellij-erlang/files/10332853/intellij-erlang-0.11.SNAPSHOT.zip)
